In [ ]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('data/softmax.txt', sep=' ', header=None)
df

   0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [ ]:
x_data = df.iloc[:, :2].values
y_data = df.iloc[:, 2:].values

In [ ]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [ ]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[2,3])) # [특정데이터 갯수, 라벨의 갯수]
b = tf.Variable(initX(shape=[3])) # [라벨의 갯수]

In [ ]:
lr = 0.01
optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
for i in range(2000):
    with tf.GradientTape() as tape: # 미분 대상 함수 with로 지정
        z = tf.matmul(x,w) + b
        cost_i = tf.nn.softmax_cross_entropy_with_logits(labels=y, logits= z )
        cost = tf.reduce_mean( cost_i)
    
    gradients = tape.gradient( cost, [w,b] )
    optimizer.apply_gradients(zip(gradients, [w,b]))
    print( 'cost', cost.numpy()) #y축

print('최종w', w.numpy()) # 최종w [[ 0.15967649  0.06876978 -0.14740367]
                            #  [ 1.513369   -0.15485252 -1.7940806 ]]
print('최종b', b.numpy()) # 최종b [-9.598209    0.46163747  7.8739443 ]

cost 3.6321952
cost 3.5195045
cost 3.4086452
cost 3.2999067
cost 3.1936224
cost 3.0901704
cost 2.9899848
cost 2.893556
cost 2.8014314
cost 2.714207
cost 2.632507
cost 2.5569487
cost 2.4880824
cost 2.4263165
cost 2.371832
cost 2.3245034
cost 2.2838564
cost 2.249071
cost 2.2190523
cost 2.192544
cost 2.1682634
cost 2.1450248
cost 2.1218295
cost 2.0979142
cost 2.072757
cost 2.04606
cost 2.017714
cost 1.9877595
cost 1.956348
cost 1.9237065
cost 1.8901087
cost 1.8558495
cost 1.8212239
cost 1.7865112
cost 1.751961
cost 1.7177848
cost 1.6841481
cost 1.651168
cost 1.618915
cost 1.5874146
cost 1.5566545
cost 1.5265933
cost 1.4971707
cost 1.4683161
cost 1.4399611
cost 1.412046
cost 1.3845282
cost 1.3573866
cost 1.3306255
cost 1.3042753
cost 1.2783922
cost 1.2530563
cost 1.228368
cost 1.2044454
cost 1.1814181
cost 1.1594241
cost 1.1386039
cost 1.1190965
cost 1.1010332
cost 1.0845323
cost 1.069694
cost 1.0565948
cost 1.0452805
cost 1.0357621
cost 1.0280101
cost 1.021952
cost 1.0174713
cost 1.0144086
cost 1.0125682
cost 1.0117252
cost 1.0116372
cost 1.0120575
cost 1.0127484
cost 1.013494
cost 1.0141106
cost 1.0144548
cost 1.0144278
cost 1.0139735
cost 1.013078
cost 1.0117617
cost 1.0100738
cost 1.0080817
cost 1.0058647
cost 1.0035044
cost 1.0010792
cost 0.99865955
cost 0.99630326
cost 0.99405533
cost 0.99194634
cost 0.9899932
cost 0.9882016
cost 0.98656666
cost 0.9850763
cost 0.98371303
cost 0.9824555
cost 0.98128164
cost 0.9801692
cost 0.9790974
cost 0.97804767
cost 0.9770041
cost 0.97595406
cost 0.9748882
cost 0.9737998
cost 0.9726856
cost 0.97154427
cost 0.97037655
cost 0.96918535
cost 0.96797407
cost 0.9667473
cost 0.96550965
cost 0.9642664
cost 0.9630214
cost 0.961779
cost 0.96054274
cost 0.9593149
cost 0.95809734
cost 0.95689106
cost 0.9556963
cost 0.95451283
cost 0.9533397
cost 0.95217574
cost 0.95101935
cost 0.94986904
cost 0.94872326
cost 0.9475806
cost 0.94643956
cost 0.9452993
cost 0.94415885
cost 0.9430181
cost 0.9418763
cost 0.9407334
cost 0.93959
cost 0.93844616
cost 0.93730205
cost 0.9361585
cost 0.9350158
cost 0.9338745
cost 0.9327348
cost 0.9315973
cost 0.930462
cost 0.9293294
cost 0.9281993
cost 0.92707205
cost 0.92594737
cost 0.9248253
cost 0.9237058
cost 0.92258877
cost 0.92147404
cost 0.9203615
cost 0.919251
cost 0.91814274
cost 0.9170364
cost 0.9159318
cost 0.91482943
cost 0.9137289
cost 0.9126304
cost 0.91153395
cost 0.9104396
cost 0.9093473
cost 0.908257
cost 0.90716946
cost 0.9060839
cost 0.90500075
cost 0.90391994
cost 0.90284145
cost 0.9017657
cost 0.90069205
cost 0.89962107
cost 0.89855266
cost 0.8974866
cost 0.896423
cost 0.8953619
cost 0.8943032
cost 0.89324707
cost 0.89219344
cost 0.89114213
cost 0.8900933
cost 0.88904715
cost 0.8880035
cost 0.88696223
cost 0.8859236
cost 0.88488746
cost 0.8838538
cost 0.8828228
cost 0.8817944
cost 0.88076854
cost 0.87974524
cost 0.8787247
cost 0.87770665
cost 0.8766911
cost 0.87567836
cost 0.8746683
cost 0.8736606
cost 0.8726557
cost 0.87165356
cost 0.8706538
cost 0.86965686
cost 0.8686625
cost 0.8676708
cost 0.8666817
cost 0.86569536
cost 0.8647116
cost 0.8637305
cost 0.862752
cost 0.8617763
cost 0.860803
cost 0.85983264
cost 0.85886484
cost 0.8578996
cost 0.85693705
cost 0.8559773
cost 0.85502017
cost 0.85406554
cost 0.85311365
cost 0.85216445
cost 0.85121787
cost 0.85027385
cost 0.84933263
cost 0.8483939
cost 0.847458
cost 0.8465245
cost 0.8455938
cost 0.84466577
cost 0.84374034
cost 0.84281737
cost 0.84189725
cost 0.8409796
cost 0.8400645
cost 0.83915216
cost 0.8382424
cost 0.8373352
cost 0.8364306
cost 0.8355286
cost 0.83462924
cost 0.83373237
cost 0.83283806
cost 0.83194643
cost 0.8310572
cost 0.83017075
cost 0.8292867
cost 0.82840514
cost 0.82752645
cost 0.82665
cost 0.82577616
cost 0.82490486
cost 0.8240361
cost 0.8231698
cost 0.82230616
cost 0.82144475
cost 0.82058626
cost 0.81972986
cost 0.818876
cost 0.8180249
cost 0.817176
cost 0.8163296
cost 0.8154857
cost 0.81464434
cost 0.81380534
cost 0.8129686
cost 0.8121345
cost 0.81130284
cost 0.8104735
cost 0.8096465
cost 0.80882204
cost 0.80799997
cost 0.8071803
cost 0.806363
cost 0.80554795
cost 0.8047355
cost 0.80392516
cost 0.8031174
cost 0.8023118
cost 0.80150855
cost 0.8007076
cost 0.7999092
cost 0.79911286
cost 0.79831886
cost 0.7975273
cost 0.79673785
cost 0.7959509
cost 0.7951661
cost 0.7943835
cost 0.79360306
cost 0.7928253
cost 0.7920495
cost 0.7912759
cost 0.7905047
cost 0.7897355
cost 0.78896874
cost 0.78820395
cost 0.78744155
cost 0.7866813
cost 0.7859232
cost 0.7851672
cost 0.78441346
cost 0.7836619
cost 0.78291243
cost 0.7821651
cost 0.78142005
cost 0.78067684
cost 0.779936
cost 0.7791971
cost 0.7784605
cost 0.7777258
cost 0.7769934
cost 0.776263
cost 0.7755346
cost 0.7748084
cost 0.7740841
cost 0.7733618
cost 0.7726418
cost 0.7719236
cost 0.7712076
cost 0.7704935
cost 0.7697815
cost 0.76907146
cost 0.7683634
cost 0.7676573
cost 0.76695335
cost 0.7662513
cost 0.76555115
cost 0.7648529
cost 0.76415676
cost 0.7634624
cost 0.7627701
cost 0.7620797
cost 0.7613912
cost 0.7607047
cost 0.76002014
cost 0.7593375
cost 0.7586565
cost 0.7579776
cost 0.7573005
cost 0.7566252
cost 0.755952
cost 0.7552804
cost 0.75461066
cost 0.75394297
cost 0.75327694
cost 0.7526128
cost 0.7519505
cost 0.75129014
cost 0.75063133
cost 0.74997455
cost 0.7493194
cost 0.74866605
cost 0.7480147
cost 0.7473649
cost 0.746717
cost 0.74607056
cost 0.74542606
cost 0.7447834
cost 0.7441424
cost 0.74350315
cost 0.74286556
cost 0.7422297
cost 0.7415957
cost 0.74096316
cost 0.7403325
cost 0.7397034
cost 0.73907614
cost 0.7384506
cost 0.73782647
cost 0.7372041
cost 0.7365834
cost 0.7359644
cost 0.73534715
cost 0.73473126
cost 0.73411715
cost 0.73350465
cost 0.73289394
cost 0.7322845
cost 0.7316769
cost 0.73107076
cost 0.73046625
cost 0.72986346
cost 0.72926205
cost 0.7286624
cost 0.7280642
cost 0.72746754
cost 0.72687244
cost 0.72627914
cost 0.725687
cost 0.7250966
cost 0.7245076
cost 0.72392035
cost 0.72333443
cost 0.72275007
cost 0.7221672
cost 0.7215858
cost 0.72100604
cost 0.72042763
cost 0.7198508
cost 0.71927536
cost 0.71870136
cost 0.71812886
cost 0.71755785
cost 0.7169882
cost 0.71642005
cost 0.71585333
cost 0.715288
cost 0.7147241
cost 0.71416175
cost 0.71360075
cost 0.71304107
cost 0.7124829
cost 0.7119261
cost 0.7113707
cost 0.71081674
cost 0.7102642
cost 0.7097128
cost 0.7091629
cost 0.7086143
cost 0.7080672
cost 0.7075213
cost 0.70697683
cost 0.7064338
cost 0.70589197
cost 0.7053515
cost 0.70481235
cost 0.7042745
cost 0.7037381
cost 0.7032027
cost 0.7026688
cost 0.7021363
cost 0.70160496
cost 0.70107484
cost 0.70054615
cost 0.70001876
cost 0.6994926
cost 0.69896775
cost 0.69844395
cost 0.69792163
cost 0.69740045
cost 0.69688046
cost 0.69636184
cost 0.69584435
cost 0.69532824
cost 0.69481313
cost 0.69429946
cost 0.69378686
cost 0.69327563
cost 0.6927655
cost 0.69225645
cost 0.69174886
cost 0.6912422
cost 0.6907369
cost 0.6902327
cost 0.6897298
cost 0.6892278
cost 0.68872726
cost 0.6882278
cost 0.68772936
cost 0.6872322
cost 0.6867361
cost 0.68624127
cost 0.6857475
cost 0.68525493
cost 0.68476343
cost 0.684273
cost 0.6837839
cost 0.6832956
cost 0.6828085
cost 0.68232256
cost 0.6818378
cost 0.6813539
cost 0.68087155
cost 0.6803898
cost 0.67990947
cost 0.67943
cost 0.6789517
cost 0.67847437
cost 0.67799824
cost 0.6775231
cost 0.67704904
cost 0.676576
cost 0.676104
cost 0.67563313
cost 0.67516315
cost 0.6746943
cost 0.6742265
cost 0.6737597
cost 0.673294
cost 0.67282915
cost 0.6723653
cost 0.67190254
cost 0.67144096
cost 0.6709802
cost 0.67052054
cost 0.6700617
cost 0.66960394
cost 0.6691471
cost 0.6686913
cost 0.6682365
cost 0.66778255
cost 0.66732967
cost 0.66687787
cost 0.6664268
cost 0.66597676
cost 0.6655277
cost 0.6650796
cost 0.6646325
cost 0.66418624
cost 0.663741
cost 0.6632965
cost 0.6628531
cost 0.66241056
cost 0.66196907
cost 0.66152835
cost 0.66108865
cost 0.66064984
cost 0.66021186
cost 0.6597747
cost 0.6593387
cost 0.65890336
cost 0.65846896
cost 0.65803564
cost 0.657603
cost 0.65717113
cost 0.6567404
cost 0.6563104
cost 0.65588135
cost 0.6554532
cost 0.6550257
cost 0.65459925
cost 0.6541736
cost 0.6537488
cost 0.65332484
cost 0.6529017
cost 0.65247947
cost 0.652058
cost 0.6516375
cost 0.6512176
cost 0.6507987
cost 0.6503806
cost 0.6499633
cost 0.64954674
cost 0.64913106
cost 0.6487163
cost 0.6483022
cost 0.64788896
cost 0.6474765
cost 0.6470648
cost 0.6466539
cost 0.64624393
cost 0.64583474
cost 0.6454263
cost 0.64501834
cost 0.6446116
cost 0.64420545
cost 0.6438
cost 0.6433953
cost 0.6429914
cost 0.6425883
cost 0.64218605
cost 0.6417845
cost 0.64138365
cost 0.6409836
cost 0.64058435
cost 0.6401856
cost 0.6397878
cost 0.6393907
cost 0.63899434
cost 0.6385987
cost 0.63820374
cost 0.6378096
cost 0.6374161
cost 0.6370233
cost 0.6366313
cost 0.63624007
cost 0.6358493
cost 0.6354594
cost 0.6350702
cost 0.6346817
cost 0.634294
cost 0.63390684
cost 0.6335205
cost 0.6331347
cost 0.6327497
cost 0.63236535
cost 0.6319818
cost 0.6315988
cost 0.6312164
cost 0.63083494
cost 0.63045394
cost 0.63007355
cost 0.62969404
cost 0.62931526
cost 0.62893677
cost 0.6285592
cost 0.6281823
cost 0.62780595
cost 0.6274303
cost 0.62705517
cost 0.62668085
cost 0.62630725
cost 0.62593406
cost 0.6255617
cost 0.6251898
cost 0.6248186
cost 0.62444806
cost 0.62407815
cost 0.62370884
cost 0.62334025
cost 0.62297225
cost 0.6226048
cost 0.622238
cost 0.6218717
cost 0.6215062
cost 0.6211412
cost 0.62077683
cost 0.62041306
cost 0.62004995
cost 0.6196873
cost 0.6193253
cost 0.61896396
cost 0.6186032
cost 0.6182429
cost 0.61788344
cost 0.6175244
cost 0.6171659
cost 0.6168082
cost 0.6164509
cost 0.6160941
cost 0.61573803
cost 0.61538243
cost 0.6150276
cost 0.614673
cost 0.6143193
cost 0.6139659
cost 0.61361325
cost 0.6132611
cost 0.6129095
cost 0.6125584
cost 0.612208
cost 0.611858
cost 0.61150855
cost 0.6111598
cost 0.61081153
cost 0.61046374
cost 0.6101165
cost 0.6097698
cost 0.60942364
cost 0.6090781
cost 0.60873294
cost 0.6083884
cost 0.6080445
cost 0.60770094
cost 0.607358
cost 0.6070156
cost 0.6066736
cost 0.6063321
cost 0.6059913
cost 0.6056508
cost 0.60531104
cost 0.60497177
cost 0.6046329
cost 0.60429454
cost 0.6039566
cost 0.6036193
cost 0.6032826
cost 0.6029462
cost 0.6026104
cost 0.60227513
cost 0.6019402
cost 0.60160595
cost 0.6012722
cost 0.6009387
cost 0.60060585
cost 0.6002734
cost 0.59994143
cost 0.59961003
cost 0.59927905
cost 0.59894866
cost 0.59861857
cost 0.59828913
cost 0.59796
cost 0.59763145
cost 0.59730345
cost 0.59697586
cost 0.5966486
cost 0.5963219
cost 0.59599566
cost 0.59566987
cost 0.59534454
cost 0.5950197
cost 0.5946953
cost 0.59437126
cost 0.5940478
cost 0.5937247
cost 0.59340227
cost 0.59308004
cost 0.5927583
cost 0.592437
cost 0.59211624
cost 0.5917959
cost 0.59147596
cost 0.59115654
cost 0.5908374
cost 0.5905189
cost 0.59020066
cost 0.58988285
cost 0.58956563
cost 0.58924866
cost 0.5889323
cost 0.58861625
cost 0.58830047
cost 0.5879854
cost 0.58767056
cost 0.5873563
cost 0.5870424
cost 0.5867289
cost 0.58641565
cost 0.5861031
cost 0.5857909
cost 0.585479
cost 0.5851675
cost 0.58485657
cost 0.58454597
cost 0.58423567
cost 0.58392584
cost 0.5836165
cost 0.58330745
cost 0.58299875
cost 0.58269066
cost 0.5823828
cost 0.5820755
cost 0.5817684
cost 0.5814619
cost 0.58115554
cost 0.5808497
cost 0.58054435
cost 0.5802394
cost 0.5799346
cost 0.5796305
cost 0.5793265
cost 0.57902294
cost 0.57871985
cost 0.57841706
cost 0.5781148
cost 0.5778127
cost 0.5775112
cost 0.57720995
cost 0.576909
cost 0.57660854
cost 0.5763085
cost 0.5760087
cost 0.57570934
cost 0.5754105
cost 0.5751117
cost 0.5748135
cost 0.5745156
cost 0.5742181
cost 0.5739209
cost 0.57362413
cost 0.57332766
cost 0.57303166
cost 0.5727359
cost 0.57244056
cost 0.5721455
cost 0.5718508
cost 0.57155645
cost 0.5712625
cost 0.570969
cost 0.5706758
cost 0.57038295
cost 0.5700902
cost 0.5697981
cost 0.5695062
cost 0.56921476
cost 0.56892353
cost 0.5686328
cost 0.56834245
cost 0.56805223
cost 0.5677625
cost 0.5674729
cost 0.56718385
cost 0.566895
cost 0.5666066
cost 0.5663185
cost 0.5660306
cost 0.5657432
cost 0.56545615
cost 0.5651693
cost 0.564883
cost 0.56459665
cost 0.5643109
cost 0.56402564
cost 0.56374025
cost 0.5634556
cost 0.5631711
cost 0.56288683
cost 0.56260294
cost 0.5623195
cost 0.56203634
cost 0.5617535
cost 0.5614707
cost 0.5611885
cost 0.5609066
cost 0.5606249
cost 0.5603436
cost 0.56006265
cost 0.559782
cost 0.55950165
cost 0.5592215
cost 0.55894184
cost 0.5586625
cost 0.5583832
cost 0.5581044
cost 0.5578259
cost 0.55754757
cost 0.5572697
cost 0.55699205
cost 0.5567149
cost 0.55643773
cost 0.55616105
cost 0.5558847
cost 0.55560863
cost 0.5553327
cost 0.55505717
cost 0.55478203
cost 0.5545071
cost 0.5542325
cost 0.5539581
cost 0.5536841
cost 0.55341035
cost 0.55313694
cost 0.5528637
cost 0.5525909
cost 0.55231833
cost 0.55204606
cost 0.5517739
cost 0.5515022
cost 0.55123085
cost 0.5509596
cost 0.55068886
cost 0.55041814
cost 0.5501479
cost 0.5498779
cost 0.5496082
cost 0.5493385
cost 0.5490695
cost 0.5488005
cost 0.54853195
cost 0.5482636
cost 0.5479955
cost 0.5477278
cost 0.5474602
cost 0.54719293
cost 0.546926
cost 0.5466594
cost 0.5463928
cost 0.5461267
cost 0.5458609
cost 0.5455952
cost 0.54532987
cost 0.5450647
cost 0.5447999
cost 0.54453546
cost 0.5442711
cost 0.5440072
cost 0.54374343
cost 0.54347986
cost 0.5432166
cost 0.5429537
cost 0.542691
cost 0.5424286
cost 0.54216635
cost 0.5419044
cost 0.5416428
cost 0.5413814
cost 0.5411203
cost 0.5408594
cost 0.54059875
cost 0.54033846
cost 0.5400783
cost 0.53981835
cost 0.53955877
cost 0.5392995
cost 0.5390404
cost 0.5387815
cost 0.53852284
cost 0.53826463
cost 0.53800654
cost 0.53774863
cost 0.5374911
cost 0.53723365
cost 0.5369766
cost 0.5367198
cost 0.53646326
cost 0.5362067
cost 0.53595066
cost 0.53569484
cost 0.53543913
cost 0.5351838
cost 0.53492874
cost 0.5346738
cost 0.5344191
cost 0.5341648
cost 0.5339106
cost 0.5336566
cost 0.5334029
cost 0.5331495
cost 0.5328964
cost 0.5326433
cost 0.53239053
cost 0.53213805
cost 0.53188586
cost 0.5316338
cost 0.531382
cost 0.53113043
cost 0.53087914
cost 0.5306279
cost 0.5303772
cost 0.5301265
cost 0.52987623
cost 0.52962595
cost 0.52937615
cost 0.5291263
cost 0.5288769
cost 0.52862763
cost 0.5283786
cost 0.5281298
cost 0.52788115
cost 0.5276328
cost 0.5273848
cost 0.5271369
cost 0.5268892
cost 0.5266417
cost 0.5263945
cost 0.5261476
cost 0.5259009
cost 0.52565426
cost 0.5254079
cost 0.5251618
cost 0.52491605
cost 0.52467024
cost 0.5244248
cost 0.52417964
cost 0.52393466
cost 0.52368987
cost 0.5234453
cost 0.523201
cost 0.52295685
cost 0.5227128
cost 0.5224693
cost 0.52222574
cost 0.52198243
cost 0.52173936
cost 0.5214964
cost 0.52125394
cost 0.5210116
cost 0.5207693
cost 0.52052724
cost 0.5202855
cost 0.5200439
cost 0.51980275
cost 0.5195615
cost 0.5193206
cost 0.51907986
cost 0.51883936
cost 0.51859903
cost 0.51835895
cost 0.51811916
cost 0.51787937
cost 0.5176398
cost 0.51740074
cost 0.51716167
cost 0.5169227
cost 0.5166842
cost 0.51644576
cost 0.51620746
cost 0.5159694
cost 0.5157316
cost 0.515494
cost 0.5152565
cost 0.51501936
cost 0.5147822
cost 0.51454544
cost 0.5143089
cost 0.51407254
cost 0.5138362
cost 0.51360023
cost 0.5133645
cost 0.5131289
cost 0.5128934
cost 0.5126583
cost 0.51242316
cost 0.5121885
cost 0.5119537
cost 0.51171935
cost 0.5114851
cost 0.51125103
cost 0.51101726
cost 0.5107836
cost 0.5105502
cost 0.51031685
cost 0.5100838
cost 0.509851
cost 0.5096182
cost 0.5093858
cost 0.50915354
cost 0.50892144
cost 0.5086895
cost 0.5084579
cost 0.5082263
cost 0.5079949
cost 0.50776374
cost 0.5075329
cost 0.50730205
cost 0.5070716
cost 0.50684106
cost 0.50661093
cost 0.506381
cost 0.5061512
cost 0.5059215
cost 0.5056921
cost 0.5054629
cost 0.50523376
cost 0.5050049
cost 0.5047762
cost 0.5045478
cost 0.50431925
cost 0.50409114
cost 0.5038632
cost 0.5036354
cost 0.5034079
cost 0.50318044
cost 0.5029533
cost 0.5027262
cost 0.50249934
cost 0.50227255
cost 0.5020461
cost 0.50181973
cost 0.5015936
cost 0.5013677
cost 0.5011418
cost 0.50091624
cost 0.5006908
cost 0.50046575
cost 0.5002406
cost 0.5000158
cost 0.4997911
cost 0.49956647
cost 0.49934217
cost 0.49911797
cost 0.498894
cost 0.4986702
cost 0.49844658
cost 0.49822307
cost 0.4979998
cost 0.49777672
cost 0.49755383
cost 0.4973309
cost 0.4971084
cost 0.496886
cost 0.4966637
cost 0.49644172
cost 0.49621993
cost 0.495998
cost 0.49577656
cost 0.4955552
cost 0.49533397
cost 0.49511296
cost 0.49489218
cost 0.49467146
cost 0.49445096
cost 0.49423057
cost 0.49401045
cost 0.49379042
cost 0.49357063
cost 0.4933509
cost 0.49313143
cost 0.49291208
cost 0.49269295
cost 0.49247402
cost 0.49225518
cost 0.4920365
cost 0.49181813
cost 0.49159974
cost 0.49138147
cost 0.49116355
cost 0.4909457
cost 0.49072808
cost 0.49051055
cost 0.49029323
cost 0.49007615
cost 0.4898591
cost 0.48964226
cost 0.4894255
cost 0.48920918
cost 0.4889928
cost 0.48877668
cost 0.4885606
cost 0.48834485
cost 0.48812914
cost 0.4879136
cost 0.48769826
cost 0.48748314
cost 0.48726812
cost 0.4870533
cost 0.48683852
cost 0.48662397
cost 0.48640954
cost 0.48619545
cost 0.4859812
cost 0.48576736
cost 0.48555362
cost 0.48534012
cost 0.48512673
cost 0.48491335
cost 0.48470026
cost 0.4844873
cost 0.4842746
cost 0.4840618
cost 0.48384953
cost 0.4836372
cost 0.48342496
cost 0.48321307
cost 0.48300123
cost 0.48278943
cost 0.48257798
cost 0.48236665
cost 0.48215532
cost 0.48194426
cost 0.4817334
cost 0.48152268
cost 0.48131207
cost 0.4811017
cost 0.48089144
cost 0.48068133
cost 0.48047125
cost 0.4802614
cost 0.48005185
cost 0.4798423
cost 0.47963288
cost 0.47942364
cost 0.4792147
cost 0.47900575
cost 0.47879708
cost 0.4785884
cost 0.47837994
cost 0.4781717
cost 0.4779636
cost 0.47775552
cost 0.47754776
cost 0.47734004
cost 0.47713247
cost 0.47692502
cost 0.4767179
cost 0.47651076
cost 0.47630376
cost 0.4760971
cost 0.47589034
cost 0.47568393
cost 0.47547758
cost 0.47527137
cost 0.47506538
cost 0.47485945
cost 0.4746537
cost 0.47444806
cost 0.47424263
cost 0.47403738
cost 0.47383222
cost 0.47362727
cost 0.47342238
cost 0.47321767
cost 0.4730131
cost 0.4728086
cost 0.47260448
cost 0.4724002
cost 0.47219643
cost 0.4719924
cost 0.4717887
cost 0.4715852
cost 0.47138175
cost 0.47117844
cost 0.4709754
cost 0.47077233
cost 0.47056958
cost 0.47036698
cost 0.4701643
cost 0.46996194
cost 0.46975964
cost 0.4695575
cost 0.46935567
cost 0.46915394
cost 0.46895206
cost 0.46875066
cost 0.4685492
cost 0.46834803
cost 0.46814683
cost 0.46794584
cost 0.46774507
cost 0.46754438
cost 0.4673438
cost 0.4671434
cost 0.4669431
cost 0.46674296
cost 0.46654302
cost 0.46634308
cost 0.46614355
cost 0.46594396
cost 0.46574447
cost 0.46554518
cost 0.46534607
cost 0.46514696
cost 0.46494812
cost 0.4647494
cost 0.46455076
cost 0.4643523
cost 0.46415395
cost 0.46395585
cost 0.46375775
cost 0.4635599
cost 0.46336222
cost 0.4631644
cost 0.46296704
cost 0.46276966
cost 0.4625724
cost 0.46237534
cost 0.46217838
cost 0.46198165
cost 0.46178487
cost 0.46158844
cost 0.46139213
cost 0.46119565
cost 0.4609995
cost 0.46080357
cost 0.46060783
cost 0.46041206
cost 0.46021634
cost 0.46002087
cost 0.45982563
cost 0.45963037
cost 0.45943537
cost 0.45924038
cost 0.45904568
cost 0.45885098
cost 0.45865643
cost 0.45846215
cost 0.45826787
cost 0.4580738
cost 0.45787966
cost 0.45768586
cost 0.4574922
cost 0.45729855
cost 0.45710507
cost 0.45691174
cost 0.45671853
cost 0.45652562
cost 0.45633256
cost 0.45613974
cost 0.4559471
cost 0.45575458
cost 0.45556208
cost 0.4553699
cost 0.45517772
cost 0.45498565
cost 0.4547938
cost 0.4546021
cost 0.4544104
cost 0.4542189
cost 0.4540275
cost 0.45383626
cost 0.4536453
cost 0.45345426
cost 0.45326334
cost 0.45307267
cost 0.45288214
cost 0.45269164
cost 0.45250118
cost 0.45231107
cost 0.45212096
cost 0.45193097
cost 0.4517412
cost 0.45155153
cost 0.45136195
cost 0.4511725
cost 0.45098308
cost 0.45079398
cost 0.4506049
cost 0.45041597
cost 0.45022723
cost 0.45003843
cost 0.44984987
cost 0.44966146
cost 0.44947314
cost 0.44928494
cost 0.44909683
cost 0.4489089
cost 0.448721
cost 0.44853342
cost 0.44834584
cost 0.44815856
cost 0.44797114
cost 0.44778395
cost 0.4475969

In [ ]:
def hxFn( xd ):
    xd = tf.constant(xd, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.softmax(z)
    return hx.numpy(), np.argmax( hx.numpy(), axis=1)

In [ ]:
hxFn( [[5,6]] )

(array([[0.5531025 , 0.42928278, 0.0176147 ]], dtype=float32), array([0]))

In [ ]:
# 토론 후
# iris 데이터 셋 학습 첫 번째, 두 번째 행의 분류를 예측

In [ ]:
from keras.utils import to_categorical

In [ ]:
xdata = np.array([0,0,0,1,1,1,2,2,2]) 
to_categorical(xdata) # 원핫으로 변경

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris(as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
x_data = iris['data'].values
y_data = to_categorical(iris['target'])

In [ ]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [ ]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[4,3])) # [특정데이터 갯수, 라벨의 갯수]
b = tf.Variable(initX(shape=[3])) # [라벨의 갯수]

In [ ]:
lr = 0.01
optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
for i in range(2000):
    with tf.GradientTape() as tape: # 미분 대상 함수 with로 지정
        z = tf.matmul(x,w) + b
        cost_i = tf.nn.softmax_cross_entropy_with_logits(labels=y, logits= z )
        cost = tf.reduce_mean( cost_i)
    
    gradients = tape.gradient( cost, [w,b] )
    optimizer.apply_gradients(zip(gradients, [w,b]))
    print( 'cost', cost.numpy()) #y축

print('최종w', w.numpy()) #최종w [[ 0.86472356  0.7664048  -0.6165995 ]
                            #   [ 2.8612015   0.27341866 -1.9434301 ]
                            #   [-2.7304587  -0.327513    1.5811676 ]
                            #   [-3.537929   -1.9434179   3.9583986 ]]
print('최종b', b.numpy()) # 최종b [ 1.5409434  2.174335  -1.8778523]

cost 8.00314
cost 7.8271356
cost 7.6511865
cost 7.475306
cost 7.299515
cost 7.123836
cost 6.9482975
cost 6.772936
cost 6.5977955
cost 6.422933
cost 6.248418
cost 6.0743375
cost 5.900797
cost 5.727927
cost 5.5558877
cost 5.38487
cost 5.2151027
cost 5.046856
cost 4.880445
cost 4.71623
cost 4.5546117
cost 4.3960285
cost 4.240945
cost 4.0898385
cost 3.9431837
cost 3.8014364
cost 3.6650195
cost 3.5343099
cost 3.409629
cost 3.2912369
cost 3.1793096
cost 3.0739143
cost 2.9749653
cost 2.8821752
cost 2.7950127
cost 2.712702
cost 2.6342628
cost 2.5585985
cost 2.484603
cost 2.411262
cost 2.3377333
cost 2.2633874
cost 2.1878197
cost 2.1108375
cost 2.0324311
cost 1.9527354
cost 1.8719946
cost 1.790523
cost 1.7086763
cost 1.6268281
cost 1.5453514
cost 1.464613
cost 1.3849721
cost 1.306787
cost 1.2304268
cost 1.1562885
cost 1.0848134
cost 1.0165033
cost 0.95193124
cost 0.8917418
cost 0.83663446
cost 0.787327
cost 0.7444931
cost 0.70867985
cost 0.6802124
cost 0.65910894
cost 0.64502686
cost 0.6372606
cost 0.6347974
cost 0.6364181
cost 0.6408217
cost 0.6467461
cost 0.65306604
cost 0.6588586
cost 0.66343474
cost 0.6663447
cost 0.6673621
cost 0.6664555
cost 0.66375303
cost 0.65950346
cost 0.65403694
cost 0.64772743
cost 0.64095855
cost 0.63409287
cost 0.6274482
cost 0.62127966
cost 0.6157689
cost 0.6110213
cost 0.60706955
cost 0.60388356
cost 0.6013834
cost 0.5994549
cost 0.5979653
cost 0.59677756
cost 0.59576213
cost 0.5948061
cost 0.5938182
cost 0.5927324
cost 0.5915078
cost 0.5901262
cost 0.5885903
cost 0.5869181
cost 0.58513904
cost 0.58328944
cost 0.58140767
cost 0.5795313
cost 0.57769305
cost 0.57591957
cost 0.5742296
cost 0.5726337
cost 0.57113445
cost 0.56972766
cost 0.56840336
cost 0.56714785
cost 0.5659449
cost 0.5647778
cost 0.5636307
cost 0.5624898
cost 0.56134397
cost 0.56018555
cost 0.55900973
cost 0.5578154
cost 0.55660367
cost 0.5553781
cost 0.55414337
cost 0.552905
cost 0.55166876
cost 0.55043954
cost 0.5492218
cost 0.5480189
cost 0.5468325
cost 0.5456637
cost 0.5445122
cost 0.54337686
cost 0.54225594
cost 0.5411474
cost 0.5400489
cost 0.5389583
cost 0.537874
cost 0.5367943
cost 0.5357182
cost 0.53464526
cost 0.5335752
cost 0.532508
cost 0.5314446
cost 0.5303852
cost 0.52933043
cost 0.52828103
cost 0.5272375
cost 0.5262002
cost 0.5251694
cost 0.52414507
cost 0.5231272
cost 0.5221155
cost 0.52110994
cost 0.5201099
cost 0.5191152
cost 0.5181255
cost 0.5171404
cost 0.51615983
cost 0.51518357
cost 0.51421154
cost 0.5132438
cost 0.5122803
cost 0.511321
cost 0.5103661
cost 0.50941557
cost 0.5084695
cost 0.50752807
cost 0.506591
cost 0.5056586
cost 0.5047307
cost 0.5038071
cost 0.5028879
cost 0.501973
cost 0.5010623
cost 0.50015557
cost 0.49925297
cost 0.49835435
cost 0.49745956
cost 0.4965687
cost 0.4956816
cost 0.49479833
cost 0.49391893
cost 0.49304315
cost 0.4921711
cost 0.49130285
cost 0.49043828
cost 0.48957738
cost 0.4887201
cost 0.4878664
cost 0.48701635
cost 0.48616973
cost 0.48532674
cost 0.4844871
cost 0.48365086
cost 0.48281816
cost 0.48198864
cost 0.48116252
cost 0.4803397
cost 0.47952017
cost 0.47870383
cost 0.47789067
cost 0.47708073
cost 0.47627395
cost 0.47547033
cost 0.4746698
cost 0.47387227
cost 0.4730779
cost 0.47228658
cost 0.47149822
cost 0.47071284
cost 0.46993038
cost 0.46915096
cost 0.46837434
cost 0.4676006
cost 0.4668297
cost 0.4660616
cost 0.4652964
cost 0.4645339
cost 0.46377417
cost 0.46301717
cost 0.46226293
cost 0.46151137
cost 0.46076244
cost 0.46001616
cost 0.45927256
cost 0.4585315
cost 0.45779306
cost 0.45705715
cost 0.45632386
cost 0.45559302
cost 0.4548647
cost 0.45413885
cost 0.4534155
cost 0.45269465
cost 0.45197618
cost 0.45125997
cost 0.45054635
cost 0.44983506
cost 0.44912606
cost 0.44841945
cost 0.44771516
cost 0.44701308
cost 0.44631332
cost 0.4456159
cost 0.44492066
cost 0.4442277
cost 0.44353694
cost 0.44284835
cost 0.442162
cost 0.44147778
cost 0.4407957
cost 0.4401158
cost 0.43943802
cost 0.4387623
cost 0.43808874
cost 0.4374172
cost 0.43674773
cost 0.43608034
cost 0.43541494
cost 0.4347516
cost 0.43409026
cost 0.43343088
cost 0.4327735
cost 0.43211803
cost 0.43146458
cost 0.4308131
cost 0.43016347
cost 0.42951578
cost 0.42887
cost 0.4282261
cost 0.42758408
cost 0.42694387
cost 0.42630556
cost 0.42566916
cost 0.42503443
cost 0.42440164
cost 0.4237706
cost 0.42314136
cost 0.42251393
cost 0.42188826
cost 0.42126426
cost 0.4206421
cost 0.42002165
cost 0.41940296
cost 0.41878596
cost 0.41817066
cost 0.41755703
cost 0.4169451
cost 0.41633487
cost 0.4157263
cost 0.41511935
cost 0.4145141
cost 0.41391042
cost 0.41330838
cost 0.412708
cost 0.4121092
cost 0.41151196
cost 0.41091636
cost 0.41032228
cost 0.40972987
cost 0.4091389
cost 0.40854958
cost 0.4079618
cost 0.40737545
cost 0.40679073
cost 0.40620744
cost 0.40562573
cost 0.4050455
cost 0.40446675
cost 0.40388948
cost 0.4033137
cost 0.4027394
cost 0.40216658
cost 0.40159518
cost 0.40102518
cost 0.4004567
cost 0.39988962
cost 0.39932394
cost 0.39875972
cost 0.39819688
cost 0.3976354
cost 0.39707538
cost 0.3965167
cost 0.3959594
cost 0.39540356
cost 0.394849
cost 0.3942958
cost 0.39374396
cost 0.39319354
cost 0.39264438
cost 0.39209655
cost 0.39155006
cost 0.3910049
cost 0.39046106
cost 0.38991854
cost 0.38937724
cost 0.3888373
cost 0.38829866
cost 0.3877613
cost 0.3872252
cost 0.38669038
cost 0.3861568
cost 0.38562447
cost 0.38509342
cost 0.38456368
cost 0.3840351
cost 0.38350776
cost 0.3829817
cost 0.3824568
cost 0.38193318
cost 0.38141075
cost 0.38088953
cost 0.3803695
cost 0.37985072
cost 0.37933308
cost 0.37881666
cost 0.37830138
cost 0.37778735
cost 0.37727448
cost 0.37676272
cost 0.37625217
cost 0.3757428
cost 0.3752345
cost 0.37472746
cost 0.37422153
cost 0.37371668
cost 0.37321302
cost 0.3727105
cost 0.3722091
cost 0.3717088
cost 0.37120965
cost 0.37071154
cost 0.3702146
cost 0.36971882
cost 0.36922404
cost 0.3687304
cost 0.36823785
cost 0.36774635
cost 0.367256
cost 0.36676672
cost 0.36627847
cost 0.36579135
cost 0.36530527
cost 0.3648202
cost 0.36433628
cost 0.3638534
cost 0.36337152
cost 0.3628907
cost 0.36241096
cost 0.36193225
cost 0.36145455
cost 0.36097795
cost 0.36050233
cost 0.36002773
cost 0.35955414
cost 0.3590816
cost 0.35861006
cost 0.35813954
cost 0.35767004
cost 0.35720155
cost 0.35673404
cost 0.3562675
cost 0.355802
cost 0.35533753
cost 0.35487396
cost 0.35441145
cost 0.35394984
cost 0.35348925
cost 0.35302967
cost 0.352571
cost 0.3521133
cost 0.35165665
cost 0.35120088
cost 0.3507461
cost 0.35029227
cost 0.3498394
cost 0.3493875
cost 0.34893653
cost 0.34848642
cost 0.3480373
cost 0.3475892
cost 0.34714195
cost 0.34669563
cost 0.34625027
cost 0.34580585
cost 0.3453623
cost 0.34491977
cost 0.344478
cost 0.34403735
cost 0.34359747
cost 0.34315857
cost 0.3427205
cost 0.34228337
cost 0.34184715
cost 0.3414118
cost 0.3409774
cost 0.34054384
cost 0.3401112
cost 0.33967942
cost 0.33924857
cost 0.33881855
cost 0.33838946
cost 0.33796123
cost 0.33753386
cost 0.33710736
cost 0.33668178
cost 0.336257
cost 0.3358331
cost 0.33541012
cost 0.33498794
cost 0.33456665
cost 0.33414623
cost 0.3337266
cost 0.33330786
cost 0.33288997
cost 0.33247292
cost 0.3320567
cost 0.33164132
cost 0.3312268
cost 0.33081314
cost 0.3304003
cost 0.3299882
cost 0.32957703
cost 0.32916668
cost 0.32875714
cost 0.32834843
cost 0.32794052
cost 0.32753345
cost 0.32712722
cost 0.3267218
cost 0.32631713
cost 0.32591334
cost 0.32551032
cost 0.3251081
cost 0.3247067
cost 0.3243061
cost 0.3239063
cost 0.3235073
cost 0.3231091
cost 0.32271168
cost 0.32231507
cost 0.32191926
cost 0.32152417
cost 0.32112992
cost 0.32073644
cost 0.32034373
cost 0.31995186
cost 0.3195607
cost 0.31917036
cost 0.3187807
cost 0.31839195
cost 0.31800386
cost 0.31761664
cost 0.31723008
cost 0.31684437
cost 0.31645933
cost 0.31607515
cost 0.31569165
cost 0.31530893
cost 0.31492698
cost 0.3145458
cost 0.31416532
cost 0.31378564
cost 0.31340665
cost 0.31302842
cost 0.31265098
cost 0.31227428
cost 0.31189823
cost 0.311523
cost 0.31114846
cost 0.3107747
cost 0.31040165
cost 0.31002933
cost 0.30965775
cost 0.3092869
cost 0.30891675
cost 0.30854735
cost 0.3081787
cost 0.30781066
cost 0.3074435
cost 0.30707693
cost 0.3067111
cost 0.306346
cost 0.30598164
cost 0.30561793
cost 0.305255
cost 0.3048927
cost 0.3045312
cost 0.30417028
cost 0.30381012
cost 0.30345064
cost 0.30309194
cost 0.3027339
cost 0.3023765
cost 0.30201986
cost 0.3016639
cost 0.30130857
cost 0.30095398
cost 0.30060008
cost 0.30024692
cost 0.29989436
cost 0.29954252
cost 0.29919133
cost 0.29884082
cost 0.29849106
cost 0.29814187
cost 0.29779342
cost 0.29744563
cost 0.29709852
cost 0.2967521
cost 0.29640627
cost 0.2960612
cost 0.29571673
cost 0.29537296
cost 0.29502985
cost 0.29468736
cost 0.29434562
cost 0.29400447
cost 0.29366398
cost 0.29332414
cost 0.292985
cost 0.2926465
cost 0.2923086
cost 0.2919714
cost 0.2916348
cost 0.29129887
cost 0.29096362
cost 0.290629
cost 0.290295
cost 0.28996164
cost 0.28962895
cost 0.28929684
cost 0.28896543
cost 0.28863466
cost 0.28830445
cost 0.2879749
cost 0.287646
cost 0.28731772
cost 0.28699008
cost 0.28666303
cost 0.28633663
cost 0.2860109
cost 0.28568572
cost 0.2853612
cost 0.2850373
cost 0.284714
cost 0.2843913
cost 0.28406927
cost 0.28374785
cost 0.283427
cost 0.28310677
cost 0.28278717
cost 0.28246817
cost 0.28214976
cost 0.28183198
cost 0.28151482
cost 0.28119823
cost 0.28088227
cost 0.28056687
cost 0.28025204
cost 0.27993792
cost 0.27962434
cost 0.27931136
cost 0.2789989
cost 0.27868715
cost 0.27837592
cost 0.27806532
cost 0.27775532
cost 0.27744585
cost 0.27713698
cost 0.2768287
cost 0.27652106
cost 0.27621394
cost 0.27590743
cost 0.27560145
cost 0.27529612
cost 0.27499133
cost 0.2746871
cost 0.27438346
cost 0.27408043
cost 0.27377796
cost 0.27347603
cost 0.27317467
cost 0.27287388
cost 0.27257368
cost 0.27227402
cost 0.27197495
cost 0.27167645
cost 0.2713785
cost 0.2710811
cost 0.27078426
cost 0.270488
cost 0.2701923
cost 0.26989707
cost 0.26960254
cost 0.26930845
cost 0.26901495
cost 0.26872203
cost 0.2684296
cost 0.26813775
cost 0.26784647
cost 0.2675557
cost 0.26726553
cost 0.26697585
cost 0.26668674
cost 0.26639813
cost 0.26611012
cost 0.26582262
cost 0.26553568
cost 0.26524925
cost 0.2649634
cost 0.264678
cost 0.2643932
cost 0.26410893
cost 0.26382515
cost 0.2635419
cost 0.26325926
cost 0.2629771
cost 0.2626954
cost 0.26241434
cost 0.26213378
cost 0.2618537
cost 0.26157415
cost 0.26129514
cost 0.2610166
cost 0.26073864
cost 0.2604612
cost 0.26018426
cost 0.25990778
cost 0.25963184
cost 0.2593565
cost 0.25908157
cost 0.25880718
cost 0.25853333
cost 0.25825998
cost 0.25798714
cost 0.25771478
cost 0.25744292
cost 0.25717157
cost 0.25690073
cost 0.25663042
cost 0.25636056
cost 0.25609127
cost 0.25582242
cost 0.2555541
cost 0.25528625
cost 0.25501892
cost 0.25475207
cost 0.2544857
cost 0.25421983
cost 0.25395453
cost 0.2536896
cost 0.2534252
cost 0.25316134
cost 0.25289792
cost 0.252635
cost 0.2523725
cost 0.25211057
cost 0.25184909
cost 0.2515881
cost 0.25132757
cost 0.25106752
cost 0.25080797
cost 0.2505489
cost 0.25029027
cost 0.25003216
cost 0.24977455
cost 0.24951737
cost 0.24926066
cost 0.24900444
cost 0.24874863
cost 0.24849334
cost 0.24823855
cost 0.24798416
cost 0.2477303
cost 0.24747688
cost 0.2472239
cost 0.24697138
cost 0.24671939
cost 0.2464678
cost 0.24621665
cost 0.245966
cost 0.24571581
cost 0.24546608
cost 0.2452168
cost 0.24496798
cost 0.2447196
cost 0.24447164
cost 0.24422422
cost 0.2439772
cost 0.24373062
cost 0.24348453
cost 0.24323884
cost 0.24299362
cost 0.24274887
cost 0.2425045
cost 0.24226062
cost 0.24201718
cost 0.24177419
cost 0.24153163
cost 0.2412895
cost 0.24104781
cost 0.24080658
cost 0.24056582
cost 0.24032545
cost 0.2400855
cost 0.239846
cost 0.23960696
cost 0.2393683
cost 0.23913012
cost 0.23889236
cost 0.23865502
cost 0.23841812
cost 0.23818167
cost 0.2379456
cost 0.23770998
cost 0.2374748
cost 0.23724005
cost 0.2370057
cost 0.23677178
cost 0.23653826
cost 0.23630519
cost 0.23607251
cost 0.23584025
cost 0.23560844
cost 0.23537704
cost 0.23514605
cost 0.2349155
cost 0.23468532
cost 0.23445559
cost 0.23422623
cost 0.23399732
cost 0.23376876
cost 0.2335407
cost 0.233313
cost 0.23308574
cost 0.23285884
cost 0.23263237
cost 0.23240632
cost 0.23218066
cost 0.2319554
cost 0.23173058
cost 0.23150612
cost 0.23128204
cost 0.2310584
cost 0.23083517
cost 0.23061228
cost 0.23038983
cost 0.23016778
cost 0.2299461
cost 0.22972488
cost 0.22950399
cost 0.2292835
cost 0.22906342
cost 0.22884373
cost 0.22862442
cost 0.2284055
cost 0.228187
cost 0.22796887
cost 0.22775108
cost 0.22753374
cost 0.2273168
cost 0.22710016
cost 0.22688393
cost 0.22666813
cost 0.2264527
cost 0.22623767
cost 0.22602294
cost 0.22580864
cost 0.22559474
cost 0.2253812
cost 0.225168
cost 0.22495526
cost 0.22474281
cost 0.22453077
cost 0.22431913
cost 0.22410788
cost 0.22389692
cost 0.22368637
cost 0.22347619
cost 0.22326638
cost 0.22305693
cost 0.22284785
cost 0.22263919
cost 0.22243086
cost 0.22222288
cost 0.22201528
cost 0.22180805
cost 0.22160113
cost 0.22139466
cost 0.22118849
cost 0.22098269
cost 0.22077729
cost 0.22057223
cost 0.2203675
cost 0.22016317
cost 0.21995915
cost 0.21975553
cost 0.21955226
cost 0.21934934
cost 0.21914676
cost 0.21894455
cost 0.21874267
cost 0.21854113
cost 0.21834
cost 0.21813917
cost 0.21793872
cost 0.21773863
cost 0.21753883
cost 0.2173394
cost 0.21714033
cost 0.21694158
cost 0.21674325
cost 0.21654521
cost 0.21634747
cost 0.21615015
cost 0.21595314
cost 0.21575648
cost 0.21556015
cost 0.21536417
cost 0.2151685
cost 0.2149732
cost 0.21477821
cost 0.21458359
cost 0.2143893
cost 0.21419533
cost 0.2140017
cost 0.21380839
cost 0.21361545
cost 0.21342282
cost 0.21323052
cost 0.21303856
cost 0.2128469
cost 0.21265562
cost 0.21246463
cost 0.21227399
cost 0.21208367
cost 0.21189366
cost 0.211704
cost 0.21151467
cost 0.21132565
cost 0.21113694
cost 0.21094857
cost 0.21076053
cost 0.21057281
cost 0.2103854
cost 0.2101983
cost 0.21001156
cost 0.20982508
cost 0.20963897
cost 0.20945318
cost 0.20926766
cost 0.20908248
cost 0.20889762
cost 0.20871307
cost 0.20852883
cost 0.20834494
cost 0.20816131
cost 0.20797803
cost 0.20779504
cost 0.20761238
cost 0.20743
cost 0.20724794
cost 0.20706621
cost 0.20688476
cost 0.20670365
cost 0.20652282
cost 0.20634231
cost 0.20616211
cost 0.20598221
cost 0.20580262
cost 0.2056233
cost 0.2054443
cost 0.20526561
cost 0.20508723
cost 0.20490912
cost 0.20473136
cost 0.20455384
cost 0.20437667
cost 0.20419978
cost 0.2040232
cost 0.20384689
cost 0.20367089
cost 0.20349517
cost 0.20331977
cost 0.20314467
cost 0.20296983
cost 0.2027953
cost 0.20262107
cost 0.20244712
cost 0.20227347
cost 0.2021001
cost 0.20192704
cost 0.20175426
cost 0.20158178
cost 0.20140956
cost 0.20123765
cost 0.20106602
cost 0.20089465
cost 0.20072362
cost 0.20055284
cost 0.20038237
cost 0.20021215
cost 0.20004223
cost 0.19987258
cost 0.19970323
cost 0.19953415
cost 0.19936535
cost 0.19919686
cost 0.19902861
cost 0.19886066
cost 0.19869299
cost 0.19852558
cost 0.19835846
cost 0.19819161
cost 0.19802505
cost 0.19785874
cost 0.1976927
cost 0.19752698
cost 0.19736148
cost 0.1971963
cost 0.1970314
cost 0.19686672
cost 0.19670235
cost 0.19653822
cost 0.19637439
cost 0.19621082
cost 0.19604751
cost 0.19588448
cost 0.19572172
cost 0.1955592
cost 0.19539697
cost 0.195235
cost 0.1950733
cost 0.19491185
cost 0.1947507
cost 0.19458976
cost 0.19442911
cost 0.19426876
cost 0.19410864
cost 0.19394878
cost 0.19378918
cost 0.19362983
cost 0.19347075
cost 0.19331194
cost 0.1931534
cost 0.1929951
cost 0.19283703
cost 0.19267924
cost 0.19252175
cost 0.19236447
cost 0.19220743
cost 0.19205068
cost 0.19189417
cost 0.19173792
cost 0.19158192
cost 0.19142617
cost 0.19127066
cost 0.19111542
cost 0.19096044
cost 0.1908057
cost 0.19065122
cost 0.19049695
cost 0.19034295
cost 0.19018923
cost 0.19003573
cost 0.18988249
cost 0.18972947
cost 0.18957672
cost 0.18942422
cost 0.18927196
cost 0.18911994
cost 0.18896815
cost 0.18881662
cost 0.18866535
cost 0.18851428
cost 0.18836348
cost 0.18821293
cost 0.18806261
cost 0.18791254
cost 0.18776272
cost 0.1876131
cost 0.18746372
cost 0.18731463
cost 0.18716574
cost 0.1870171
cost 0.18686871
cost 0.18672052
cost 0.1865726
cost 0.18642491
cost 0.18627743
cost 0.18613018
cost 0.1859832
cost 0.18583645
cost 0.18568991
cost 0.18554363
cost 0.18539755
cost 0.18525171
cost 0.18510613
cost 0.18496075
cost 0.18481562
cost 0.18467075
cost 0.18452604
cost 0.18438159
cost 0.18423738
cost 0.18409337
cost 0.1839496
cost 0.18380606
cost 0.18366277
cost 0.18351966
cost 0.1833768
cost 0.18323417
cost 0.18309174
cost 0.18294957
cost 0.18280761
cost 0.18266587
cost 0.18252435
cost 0.18238305
cost 0.18224198
cost 0.18210112
cost 0.1819605
cost 0.18182008
cost 0.18167987
cost 0.18153992
cost 0.18140016
cost 0.18126063
cost 0.18112132
cost 0.1809822
cost 0.18084332
cost 0.18070465
cost 0.18056622
cost 0.18042798
cost 0.18028997
cost 0.18015216
cost 0.18001458
cost 0.17987722
cost 0.17974004
cost 0.17960311
cost 0.17946638
cost 0.17932983
cost 0.17919354
cost 0.17905745
cost 0.17892154
cost 0.17878588
cost 0.17865042
cost 0.17851514
cost 0.17838012
cost 0.17824526
cost 0.17811064
cost 0.1779762
cost 0.17784198
cost 0.17770797
cost 0.17757417
cost 0.17744058
cost 0.17730719
cost 0.177174
cost 0.17704101
cost 0.17690825
cost 0.1767757
cost 0.17664333
cost 0.17651115
cost 0.17637917
cost 0.17624743
cost 0.17611586
cost 0.17598452
cost 0.17585334
cost 0.17572239
cost 0.17559166
cost 0.1754611
cost 0.17533074
cost 0.17520058
cost 0.17507063
cost 0.17494085
cost 0.17481132
cost 0.17468195
cost 0.17455278
cost 0.1744238
cost 0.17429504
cost 0.17416646
cost 0.17403807
cost 0.17390989
cost 0.17378189
cost 0.1736541
cost 0.1735265
cost 0.17339909
cost 0.17327185
cost 0.17314483
cost 0.17301801
cost 0.17289136
cost 0.17276491
cost 0.17263864
cost 0.17251258
cost 0.1723867
cost 0.17226101
cost 0.17213552
cost 0.1720102
cost 0.17188509
cost 0.17176016
cost 0.1716354
cost 0.17151085
cost 0.17138648
cost 0.1712623
cost 0.1711383
cost 0.17101449
cost 0.17089085
cost 0.17076744
cost 0.17064416
cost 0.1705211
cost 0.1703982
cost 0.1702755
cost 0.17015299
cost 0.17003064
cost 0.16990851
cost 0.16978654
cost 0.16966476
cost 0.16954313
cost 0.1694217
cost 0.16930047
cost 0.16917941
cost 0.1690585
cost 0.16893782
cost 0.16881728
cost 0.16869697
cost 0.16857675
cost 0.16845678
cost 0.16833697
cost 0.16821733
cost 0.16809787
cost 0.16797858
cost 0.16785948
cost 0.16774057
cost 0.16762184
cost 0.16750324
cost 0.16738485
cost 0.16726662
cost 0.16714856
cost 0.16703068
cost 0.16691299
cost 0.16679545
cost 0.16667809
cost 0.1665609
cost 0.16644388
cost 0.16632706
cost 0.16621037
cost 0.16609387
cost 0.16597754
cost 0.1658614
cost 0.1657454
cost 0.16562958
cost 0.16551395
cost 0.16539846
cost 0.16528316
cost 0.16516802
cost 0.16505304
cost 0.16493826
cost 0.16482359
cost 0.16470912
cost 0.16459483
cost 0.16448069
cost 0.16436672
cost 0.16425294
cost 0.16413929
cost 0.16402578
cost 0.1639125
cost 0.16379933
cost 0.16368636
cost 0.16357355
cost 0.16346088
cost 0.16334839
cost 0.1632361
cost 0.1631239
cost 0.16301191
cost 0.16290008
cost 0.16278839
cost 0.16267686
cost 0.16256553
cost 0.1624543
cost 0.16234326
cost 0.16223241
cost 0.16212168
cost 0.16201113
cost 0.16190073
cost 0.16179048
cost 0.16168042
cost 0.16157049
cost 0.16146073
cost 0.1613511
cost 0.16124165
cost 0.16113238
cost 0.16102326
cost 0.16091424
cost 0.16080543
cost 0.16069676
cost 0.16058823
cost 0.16047989
cost 0.1603717
cost 0.16026363
cost 0.16015573
cost 0.16004798
cost 0.1599404
cost 0.159833
cost 0.15972568
cost 0.15961856
cost 0.15951161
cost 0.15940474
cost 0.15929808
cost 0.15919158
cost 0.15908518
cost 0.15897897
cost 0.15887292
cost 0.15876698
cost 0.15866122
cost 0.1585556
cost 0.15845014
cost 0.1583448
cost 0.15823965
cost 0.15813461
cost 0.15802974
cost 0.15792501
cost 0.15782043
cost 0.157716
cost 0.15761174
cost 0.1575076
cost 0.15740357
cost 0.15729976
cost 0.15719606
cost 0.15709248
cost 0.15698908
cost 0.15688582
cost 0.15678272
cost 0.15667972
cost 0.15657689
cost 0.15647422
cost 0.15637168
cost 0.1562693
cost 0.156167

In [ ]:
w.shape

TensorShape([4, 3])

In [ ]:
def hxFn( xd ):
    xd = tf.constant(xd, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.softmax(z)
    return hx.numpy(), np.argmax( hx.numpy(), axis=1)

In [ ]:
x_data[[0,1]]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [ ]:
hxFn(x_data[[0,1]])

(array([[9.9473947e-01, 5.2605360e-03, 1.5900731e-09],
        [9.8071003e-01, 1.9289946e-02, 2.3293067e-08]], dtype=float32),
 array([0, 0]))

In [ ]:
np.argmax(y_data[[0,1]], axis=1)

array([0, 0])