In [1]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/softmax.txt', sep=' ', header=None)
df

   0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [3]:
x_data = df.iloc[:, :2].values.astype(np.float32) # 공부한 시간, 출석 일수
y_data = df.iloc[:, 2:].values # 학점

In [4]:
y_data

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [5]:
y_data.shape

(8, 3)

In [6]:
dense = Dense(units=3, input_dim=2, activation='softmax') # w: 2X3 (특성데이터 갯수, 라벨의 갯수), b:[라벨의 갯수]
dense(x_data)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[4.7676373e-02, 7.1279824e-01, 2.3952542e-01],
       [9.5408112e-03, 8.0118233e-01, 1.8927687e-01],
       [1.7667896e-03, 6.6059244e-01, 3.3764079e-01],
       [1.5264575e-04, 8.5329133e-01, 1.4655600e-01],
       [2.4294030e-05, 9.6221954e-01, 3.7756175e-02],
       [1.3096104e-03, 3.8816077e-01, 6.1052966e-01],
       [2.8417391e-05, 8.9223427e-01, 1.0773736e-01],
       [5.2267728e-06, 9.2174566e-01, 7.8249156e-02]], dtype=float32)>

In [7]:
w, b = dense.get_weights() # 학습되지 않음
print(w)
print('-'*40)
print(b)

[[-0.6096899   0.36932552 -0.36887473]
 [-0.32730907  0.41942275  0.80528426]]
----------------------------------------
[0. 0. 0.]

In [8]:
z = tf.matmul(x_data, w) + b
hx = tf.nn.softmax(z)
hx.numpy().argmax(axis=1)

array([1, 1, 1, 1, 1, 2, 1, 1])

In [9]:
w.shape

(2, 3)

In [10]:
dense = Dense(units=3, input_dim=2, activation='softmax')
model = Sequential( [dense] )
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x_data, y_data, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - acc: 0.3750 - loss: 2.6722
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 0.2500 - loss: 2.5122
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.2500 - loss: 2.0972
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.2500 - loss: 1.7275
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - acc: 0.3750 - loss: 1.4633
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.5000 - loss: 1.1939
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - acc: 0.6250 - loss: 0.9593
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step - acc: 0.3750 - loss: 0.9575
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 0.3750 - loss: 1.2101
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - acc: 0.3750 - loss: 1.3212
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 0.3750 - loss: 1.2246
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.5000 - loss: 1.0446
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - acc: 0.5000 - loss: 0.9064
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.6250 - loss: 0.8542
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 0.6250 - loss: 0.8685
Epoch 16/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.6250 - loss: 0.9164
Epoch 17/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - acc: 0.5000 - loss: 0.9592
Epoch 18/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 0.5000 - loss: 0.9720
Epoch 19/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - acc: 0.5000 - loss: 0.9562
Epoch 20/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - acc: 0.6250 - loss: 0.9277
Epoch 21/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 0.6250 - loss: 0.8956
Epoch 22/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.6250 - loss: 0.8570
Epoch 23/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 0.6250 - loss: 0.8119
Epoch 24/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - acc: 0.7500 - loss: 0.7727
Epoch 25/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step - acc: 0.6250 - loss: 0.7558
Epoch 26/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - acc: 0.5000 - loss: 0.7654
Epoch 27/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 0.5000 - loss: 0.7869
Epoch 28/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - acc: 0.5000 - loss: 0.7976
Epoch 29/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.6250 - loss: 0.7859
Epoch 30/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.6250 - loss: 0.7584
Epoch 31/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - acc: 0.7500 - loss: 0.7312
Epoch 32/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - acc: 0.7500 - loss: 0.7152
Epoch 33/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - acc: 0.7500 - loss: 0.7099
Epoch 34/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.7500 - loss: 0.7093
Epoch 35/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - acc: 0.7500 - loss: 0.7102
Epoch 36/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - acc: 0.6250 - loss: 0.7109
Epoch 37/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - acc: 0.6250 - loss: 0.7088
Epoch 38/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 0.6250 - loss: 0.7011
Epoch 39/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - acc: 0.6250 - loss: 0.6888
Epoch 40/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 0.6250 - loss: 0.6759
Epoch 41/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - acc: 0.7500 - loss: 0.6662
Epoch 42/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - acc: 0.7500 - loss: 0.6606
Epoch 43/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - acc: 0.7500 - loss: 0.6579
Epoch 44/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - acc: 0.7500 - loss: 0.6566
Epoch 45/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - acc: 0.7500 - loss: 0.6551
Epoch 46/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - acc: 0.6250 - loss: 0.6517
Epoch 47/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - acc: 0.6250 - loss: 0.6458
Epoch 48/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.6250 - loss: 0.6382
Epoch 49/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 0.6250 - loss: 0.6311
Epoch 50/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 0.7500 - loss: 0.6260
Epoch 51/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step - acc: 0.7500 - loss: 0.6232
Epoch 52/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - acc: 0.7500 - loss: 0.6213
Epoch 53/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.7500 - loss: 0.6188
Epoch 54/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 0.7500 - loss: 0.6155
Epoch 55/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - acc: 0.7500 - loss: 0.6117
Epoch 56/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.6250 - loss: 0.6074
Epoch 57/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - acc: 0.6250 - loss: 0.6029
Epoch 58/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.6250 - loss: 0.5986
Epoch 59/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - acc: 0.7500 - loss: 0.5952
Epoch 60/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.7500 - loss: 0.5926
Epoch 61/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - acc: 0.7500 - loss: 0.5904
Epoch 62/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 0.7500 - loss: 0.5878
Epoch 63/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - acc: 0.7500 - loss: 0.5848
Epoch 64/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.7500 - loss: 0.5815
Epoch 65/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - acc: 0.6250 - loss: 0.5782
Epoch 66/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.6250 - loss: 0.5750
Epoch 67/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.7500 - loss: 0.5721
Epoch 68/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - acc: 0.7500 - loss: 0.5695
Epoch 69/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - acc: 0.7500 - loss: 0.5673
Epoch 70/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - acc: 0.7500 - loss: 0.5649
Epoch 71/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - acc: 0.7500 - loss: 0.5624
Epoch 72/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 0.7500 - loss: 0.5597
Epoch 73/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.8750 - loss: 0.5570
Epoch 74/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.8750 - loss: 0.5544
Epoch 75/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - acc: 0.8750 - loss: 0.5518
Epoch 76/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - acc: 0.8750 - loss: 0.5494
Epoch 77/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.8750 - loss: 0.5472
Epoch 78/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - acc: 1.0000 - loss: 0.5450
Epoch 79/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - acc: 1.0000 - loss: 0.5428
Epoch 80/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 1.0000 - loss: 0.5404
Epoch 81/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.8750 - loss: 0.5381
Epoch 82/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - acc: 0.8750 - loss: 0.5358
Epoch 83/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - acc: 0.8750 - loss: 0.5335
Epoch 84/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - acc: 0.8750 - loss: 0.5313
Epoch 85/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.8750 - loss: 0.5292
Epoch 86/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.8750 - loss: 0.5271
Epoch 87/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 0.8750 - loss: 0.5250
Epoch 88/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 0.8750 - loss: 0.5229
Epoch 89/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - acc: 0.8750 - loss: 0.5208
Epoch 90/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.8750 - loss: 0.5187
Epoch 91/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - acc: 0.8750 - loss: 0.5167
Epoch 92/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.8750 - loss: 0.5146
Epoch 93/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - acc: 0.8750 - loss: 0.5127
Epoch 94/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - acc: 0.8750 - loss: 0.5107
Epoch 95/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - acc: 1.0000 - loss: 0.5087
Epoch 96/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 1.0000 - loss: 0.5068
Epoch 97/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - acc: 0.8750 - loss: 0.5049
Epoch 98/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - acc: 0.8750 - loss: 0.5029
Epoch 99/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - acc: 0.8750 - loss: 0.5010
Epoch 100/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - acc: 0.8750 - loss: 0.4991
Epoch 101/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 0.8750 - loss: 0.4973
Epoch 102/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8750 - loss: 0.4954
Epoch 103/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - acc: 0.8750 - loss: 0.4936
Epoch 104/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - acc: 0.8750 - loss: 0.4918
Epoch 105/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - acc: 0.8750 - loss: 0.4899
Epoch 106/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - acc: 0.8750 - loss: 0.4881
Epoch 107/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - acc: 0.8750 - loss: 0.4864
Epoch 108/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - acc: 0.8750 - loss: 0.4846
Epoch 109/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - acc: 0.8750 - loss: 0.4828
Epoch 110/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - acc: 1.0000 - loss: 0.4811
Epoch 111/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 1.0000 - loss: 0.4794
Epoch 112/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 1.0000 - loss: 0.4777
Epoch 113/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - acc: 1.0000 - loss: 0.4760
Epoch 114/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - acc: 1.0000 - loss: 0.4743
Epoch 115/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 1.0000 - loss: 0.4726
Epoch 116/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - acc: 0.8750 - loss: 0.4709
Epoch 117/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - acc: 0.8750 - loss: 0.4693
Epoch 118/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 0.8750 - loss: 0.4676
Epoch 119/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - acc: 0.8750 - loss: 0.4660
Epoch 120/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - acc: 0.8750 - loss: 0.4644
Epoch 121/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 0.8750 - loss: 0.4628
Epoch 122/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - acc: 1.0000 - loss: 0.4612
Epoch 123/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - acc: 1.0000 - loss: 0.4596
Epoch 124/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 1.0000 - loss: 0.4580
Epoch 125/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 1.0000 - loss: 0.4565
Epoch 126/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 1.0000 - loss: 0.4549
Epoch 127/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - acc: 1.0000 - loss: 0.4534
Epoch 128/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - acc: 1.0000 - loss: 0.4519
Epoch 129/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - acc: 1.0000 - loss: 0.4504
Epoch 130/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - acc: 1.0000 - loss: 0.4488
Epoch 131/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - acc: 1.0000 - loss: 0.4473
Epoch 132/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 1.0000 - loss: 0.4459
Epoch 133/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 1.0000 - loss: 0.4444
Epoch 134/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - acc: 1.0000 - loss: 0.4429
Epoch 135/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - acc: 1.0000 - loss: 0.4415
Epoch 136/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 1.0000 - loss: 0.4400
Epoch 137/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step - acc: 1.0000 - loss: 0.4386
Epoch 138/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - acc: 1.0000 - loss: 0.4371
Epoch 139/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - acc: 1.0000 - loss: 0.4357
Epoch 140/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - acc: 1.0000 - loss: 0.4343
Epoch 141/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - acc: 1.0000 - loss: 0.4329
Epoch 142/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 1.0000 - loss: 0.4315
Epoch 143/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - acc: 1.0000 - loss: 0.4301
Epoch 144/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - acc: 1.0000 - loss: 0.4288
Epoch 145/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 1.0000 - loss: 0.4274
Epoch 146/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - acc: 1.0000 - loss: 0.4260
Epoch 147/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 1.0000 - loss: 0.4247
Epoch 148/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - acc: 1.0000 - loss: 0.4233
Epoch 149/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - acc: 1.0000 - loss: 0.4220
Epoch 150/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 1.0000 - loss: 0.4207
Epoch 151/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 1.0000 - loss: 0.4194
Epoch 152/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - acc: 1.0000 - loss: 0.4181
Epoch 153/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - acc: 1.0000 - loss: 0.4168
Epoch 154/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 1.0000 - loss: 0.4155
Epoch 155/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - acc: 1.0000 - loss: 0.4142
Epoch 156/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - acc: 1.0000 - loss: 0.4129
Epoch 157/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 1.0000 - loss: 0.4116
Epoch 158/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - acc: 1.0000 - loss: 0.4104
Epoch 159/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - acc: 1.0000 - loss: 0.4091
Epoch 160/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 1.0000 - loss: 0.4079
Epoch 161/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 1.0000 - loss: 0.4066
Epoch 162/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 1.0000 - loss: 0.4054
Epoch 163/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 1.0000 - loss: 0.4042
Epoch 164/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - acc: 1.0000 - loss: 0.4030
Epoch 165/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - acc: 1.0000 - loss: 0.4018
Epoch 166/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 1.0000 - loss: 0.4006
Epoch 167/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 1.0000 - loss: 0.3994
Epoch 168/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - acc: 1.0000 - loss: 0.3982
Epoch 169/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 1.0000 - loss: 0.3970
Epoch 170/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 1.0000 - loss: 0.3958
Epoch 171/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 1.0000 - loss: 0.3947
Epoch 172/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 1.0000 - loss: 0.3935
Epoch 173/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 1.0000 - loss: 0.3924
Epoch 174/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 1.0000 - loss: 0.3912
Epoch 175/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - acc: 1.0000 - loss: 0.3901
Epoch 176/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - acc: 1.0000 - loss: 0.3889
Epoch 177/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - acc: 1.0000 - loss: 0.3878
Epoch 178/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - acc: 1.0000 - loss: 0.3867
Epoch 179/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - acc: 1.0000 - loss: 0.3856
Epoch 180/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - acc: 1.0000 - loss: 0.3845
Epoch 181/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 1.0000 - loss: 0.3834
Epoch 182/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 1.0000 - loss: 0.3823
Epoch 183/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 1.0000 - loss: 0.3812
Epoch 184/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 1.0000 - loss: 0.3801
Epoch 185/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - acc: 1.0000 - loss: 0.3790
Epoch 186/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 1.0000 - loss: 0.3780
Epoch 187/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 1.0000 - loss: 0.3769
Epoch 188/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - acc: 1.0000 - loss: 0.3759
Epoch 189/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - acc: 1.0000 - loss: 0.3748
Epoch 190/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - acc: 1.0000 - loss: 0.3738
Epoch 191/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - acc: 1.0000 - loss: 0.3727
Epoch 192/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - acc: 1.0000 - loss: 0.3717
Epoch 193/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - acc: 1.0000 - loss: 0.3707
Epoch 194/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 1.0000 - loss: 0.3696
Epoch 195/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 1.0000 - loss: 0.3686
Epoch 196/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - acc: 1.0000 - loss: 0.3676
Epoch 197/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 1.0000 - loss: 0.3666
Epoch 198/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - acc: 1.0000 - loss: 0.3656
Epoch 199/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - acc: 1.0000 - loss: 0.3646
Epoch 200/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - acc: 1.0000 - loss: 0.3636
Epoch 201/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - acc: 1.0000 - loss: 0.3626
Epoch 202/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - acc: 1.0000 - loss: 0.3617
Epoch 203/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 1.0000 - loss: 0.3607
Epoch 204/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - acc: 1.0000 - loss: 0.3597
Epoch 205/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - acc: 1.0000 - loss: 0.3588
Epoch 206/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 1.0000 - loss: 0.3578
Epoch 207/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step - acc: 1.0000 - loss: 0.3568
Epoch 208/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - acc: 1.0000 - loss: 0.3559
Epoch 209/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - acc: 1.0000 - loss: 0.3550
Epoch 210/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - acc: 1.0000 - loss: 0.3540
Epoch 211/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - acc: 1.0000 - loss: 0.3531
Epoch 212/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 1.0000 - loss: 0.3522
Epoch 213/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 1.0000 - loss: 0.3512
Epoch 214/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - acc: 1.0000 - loss: 0.3503
Epoch 215/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 1.0000 - loss: 0.3494
Epoch 216/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - acc: 1.0000 - loss: 0.3485
Epoch 217/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - acc: 1.0000 - loss: 0.3476
Epoch 218/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 1.0000 - loss: 0.3467
Epoch 219/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 1.0000 - loss: 0.3458
Epoch 220/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - acc: 1.0000 - loss: 0.3449
Epoch 221/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - acc: 1.0000 - loss: 0.3440
Epoch 222/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - acc: 1.0000 - loss: 0.3431
Epoch 223/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - acc: 1.0000 - loss: 0.3423
Epoch 224/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - acc: 1.0000 - loss: 0.3414
Epoch 225/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - acc: 1.0000 - loss: 0.3405
Epoch 226/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - acc: 1.0000 - loss: 0.3397
Epoch 227/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 1.0000 - loss: 0.3388
Epoch 228/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 1.0000 - loss: 0.3379
Epoch 229/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - acc: 1.0000 - loss: 0.3371
Epoch 230/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - acc: 1.0000 - loss: 0.3362
Epoch 231/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 1.0000 - loss: 0.3354
Epoch 232/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 1.0000 - loss: 0.3346
Epoch 233/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - acc: 1.0000 - loss: 0.3337
Epoch 234/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 1.0000 - loss: 0.3329
Epoch 235/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - acc: 1.0000 - loss: 0.3321
Epoch 236/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - acc: 1.0000 - loss: 0.3313
Epoch 237/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 1.0000 - loss: 0.3304
Epoch 238/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - acc: 1.0000 - loss: 0.3296
Epoch 239/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 1.0000 - loss: 0.3288
Epoch 240/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - acc: 1.0000 - loss: 0.3280
Epoch 241/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 1.0000 - loss: 0.3272
Epoch 242/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - acc: 1.0000 - loss: 0.3264
Epoch 243/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - acc: 1.0000 - loss: 0.3256
Epoch 244/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - acc: 1.0000 - loss: 0.3248
Epoch 245/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - acc: 1.0000 - loss: 0.3240
Epoch 246/500

In [11]:
w, b = dense.get_weights() # 학습된 데이터
print(w)
print('-'*40)
print(b)

[[-0.12174691 -0.21917146 -0.47657374]
 [ 3.2843401   0.68049604 -1.7353053 ]]
----------------------------------------
[-15.444616    -0.12660323  10.93695   ]

In [12]:
dense(x_data).numpy().argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [13]:
y_data.argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [14]:
model.predict(x_data).argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

array([2, 2, 2, 1, 1, 1, 0, 0])

## iris 데이터 셋 케라스로 학습하고
## 1,2 번째 행의 예측값을 구하시오.

In [15]:
from keras.utils import to_categorical

In [16]:
from sklearn.datasets import load_iris

In [17]:
iris = load_iris(as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [18]:
xdata = iris['data'].values
ydata = to_categorical(iris['target'])

In [19]:
xdata.shape

(150, 4)

In [20]:
ydata

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [21]:
ydata.shape

(150, 3)

In [22]:
dense = Dense(units=3, input_dim=4, activation='softmax') # w: 2X3 (특성데이터 갯수, 라벨의 갯수), b:[라벨의 갯수]
dense(xdata)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

<tf.Tensor: shape=(150, 3), dtype=float32, numpy=
array([[9.99896407e-01, 9.88888205e-05, 4.61679792e-06],
       [9.99728024e-01, 2.59589026e-04, 1.23626569e-05],
       [9.99776781e-01, 2.10801009e-04, 1.24099915e-05],
       [9.99734461e-01, 2.51808699e-04, 1.36470935e-05],
       [9.99907494e-01, 8.80441512e-05, 4.43410272e-06],
       [9.99962926e-01, 3.57863973e-05, 1.30366391e-06],
       [9.99843717e-01, 1.47242594e-04, 9.09992468e-06],
       [9.99873519e-01, 1.21010075e-04, 5.52505207e-06],
       [9.99569595e-01, 4.05296334e-04, 2.51845795e-05],
       [9.99765933e-01, 2.23964147e-04, 1.00844109e-05],
       [9.99939561e-01, 5.81488930e-05, 2.23666598e-06],
       [9.99861836e-01, 1.31840716e-04, 6.35033575e-06],
       [9.99698162e-01, 2.87587434e-04, 1.42910158e-05],
       [9.99561012e-01, 4.06788342e-04, 3.22194937e-05],
       [9.99968767e-01, 3.00365318e-05, 1.16682384e-06],
       [9.99985933e-01, 1.35394812e-05, 5.15438217e-07],
       [9.99958754e-01, 3.94084527e-05, 1.82825625e-06],
       [9.99901295e-01, 9.42982297e-05, 4.46653394e-06],
       [9.99961138e-01, 3.77671349e-05, 1.12174268e-06],
       [9.99942303e-01, 5.50993209e-05, 2.59940498e-06],
       [9.99904394e-01, 9.25754794e-05, 2.98225450e-06],
       [9.99934673e-01, 6.23446176e-05, 2.92839832e-06],
       [9.99869466e-01, 1.20770244e-04, 9.72817543e-06],
       [9.99883294e-01, 1.12305868e-04, 4.39871792e-06],
       [9.99872446e-01, 1.22644866e-04, 4.92772506e-06],
       [9.99756515e-01, 2.34159321e-04, 9.33458159e-06],
       [9.99887824e-01, 1.07415610e-04, 4.75203069e-06],
       [9.99904752e-01, 9.13760305e-05, 3.79344942e-06],
       [9.99884129e-01, 1.11069137e-04, 4.80701965e-06],
       [9.99794304e-01, 1.96099048e-04, 9.62993545e-06],
       [9.99769747e-01, 2.20250207e-04, 1.00265852e-05],
       [9.99908328e-01, 8.83369066e-05, 3.30551256e-06],
       [9.99964118e-01, 3.43313004e-05, 1.57268107e-06],
       [9.99974966e-01, 2.39697747e-05, 1.01644400e-06],
       [9.99776661e-01, 2.13568346e-04, 9.75623971e-06],
       [9.99807179e-01, 1.83148150e-04, 9.65443724e-06],
       [9.99915481e-01, 8.13244988e-05, 3.21144034e-06],
       [9.99897361e-01, 9.75423027e-05, 5.12585166e-06],
       [9.99626517e-01, 3.49915907e-04, 2.35367243e-05],
       [9.99880552e-01, 1.14544513e-04, 4.94023425e-06],
       [9.99892473e-01, 1.02051228e-04, 5.43597071e-06],
       [9.98895526e-01, 1.04535732e-03, 5.90728087e-05],
       [9.99733984e-01, 2.48545723e-04, 1.73591561e-05],
       [9.99913812e-01, 8.23160299e-05, 3.81955942e-06],
       [9.99950528e-01, 4.77123140e-05, 1.79320989e-06],
       [9.99725163e-01, 2.61510781e-04, 1.33761077e-05],
       [9.99941111e-01, 5.64057373e-05, 2.46903596e-06],
       [9.99769866e-01, 2.17396286e-04, 1.27538724e-05],
       [9.99936104e-01, 6.14314340e-05, 2.50144876e-06],
       [9.99845862e-01, 1.47089086e-04, 7.00123837e-06],
       [9.99985099e-01, 1.48498630e-05, 3.59209693e-08],
       [9.99979258e-01, 2.06592485e-05, 8.05307465e-08],
       [9.99983072e-01, 1.69157665e-05, 3.82174790e-08],
       [9.99802649e-01, 1.95905726e-04, 1.41494229e-06],
       [9.99962091e-01, 3.78439690e-05, 1.21666915e-07],
       [9.99933481e-01, 6.61530357e-05, 3.46225846e-07],
       [9.99983191e-01, 1.67140552e-05, 6.31852046e-08],
       [9.99681950e-01, 3.13337659e-04, 4.74517901e-06],
       [9.99966621e-01, 3.31999981e-05, 9.98148906e-08],
       [9.99884963e-01, 1.13827606e-04, 1.13336046e-06],
       [9.99433219e-01, 5.60177898e-04, 6.58633235e-06],
       [9.99958634e-01, 4.11498331e-05, 2.46225170e-07],
       [9.99795258e-01, 2.03718679e-04, 1.03997934e-06],
       [9.99959230e-01, 4.06699037e-05, 1.55260693e-07],
       [9.99926090e-01, 7.31660548e-05, 7.11676194e-07],
       [9.99977589e-01, 2.23346142e-05, 7.54064544e-08],
       [9.99954581e-01, 4.51349697e-05, 2.67270735e-07],
       [9.99904990e-01, 9.43627165e-05, 5.58313275e-07],
       [9.99871969e-01, 1.27582345e-04, 4.61762994e-07],
       [9.99850512e-01, 1.48379200e-04, 1.08484187e-06],
       [9.99977946e-01, 2.19292579e-05, 9.90031808e-08],
       [9.99939680e-01, 5.99089253e-05, 3.37743103e-07],
       [9.99934077e-01, 6.56428383e-05, 1.86459559e-07],
       [9.99946713e-01, 5.30716243e-05, 1.93166954e-07],
       [9.99960065e-01, 3.98328302e-05, 1.60891148e-07],
       [9.99971867e-01, 2.79981214e-05, 9.82042181e-08],
       [9.99967813e-01, 3.20742583e-05, 7.59161480e-08],
       [9.99980092e-01, 1.98853559e-05, 4.78755524e-08],
       [9.99956727e-01, 4.29945576e-05, 1.98937258e-07],
       [9.99862075e-01, 1.36692543e-04, 1.20752077e-06],
       [9.99807894e-01, 1.90535444e-04, 1.53741394e-06],
       [9.99793589e-01, 2.04684067e-04, 1.72932107e-06],
       [9.99909401e-01, 9.00422820e-05, 6.18830256e-07],
       [9.99949932e-01, 4.99526614e-05, 1.57142722e-07],
       [9.99949217e-01, 5.03746196e-05, 3.34297340e-07],
       [9.99982476e-01, 1.74288016e-05, 8.98866475e-08],
       [9.99980211e-01, 1.98120069e-05, 5.66085490e-08],
       [9.99884963e-01, 1.14657916e-04, 4.12253485e-07],
       [9.99944925e-01, 5.46606170e-05, 4.00466604e-07],
       [9.99859810e-01, 1.39144933e-04, 1.04351682e-06],
       [9.99887586e-01, 1.11673442e-04, 6.60507851e-07],
       [9.99964714e-01, 3.51108938e-05, 1.45094148e-07],
       [9.99894977e-01, 1.04297549e-04, 6.62184732e-07],
       [9.99643207e-01, 3.51922703e-04, 4.94055939e-06],
       [9.99910235e-01, 8.91451200e-05, 5.81070481e-07],
       [9.99946713e-01, 5.29666031e-05, 3.40117680e-07],
       [9.99939680e-01, 5.99314953e-05, 3.83164490e-07],
       [9.99955297e-01, 4.44570396e-05, 2.01239757e-07],
       [9.99753416e-01, 2.42548718e-04, 4.06210074e-06],
       [9.99926686e-01, 7.28484665e-05, 4.85546252e-07],
       [9.99992013e-01, 7.96493532e-06, 1.56288067e-08],
       [9.99951482e-01, 4.83417607e-05, 1.77975991e-07],
       [9.99989390e-01, 1.06251691e-05, 1.25254598e-08],
       [9.99975801e-01, 2.42537990e-05, 5.08075537e-08],
       [9.99985576e-01, 1.44297792e-05, 2.58041180e-08],
       [9.99993205e-01, 6.82033215e-06, 3.96101063e-09],
       [9.99856949e-01, 1.41789365e-04, 1.17210789e-06],
       [9.99988198e-01, 1.18304288e-05, 9.18298859e-09],
       [9.99963164e-01, 3.67827597e-05, 5.04249940e-08],
       [9.99997139e-01, 2.83892768e-06, 3.32266037e-09],
       [9.99986649e-01, 1.33421709e-05, 3.67451776e-08],
       [9.99966741e-01, 3.31351293e-05, 7.68031754e-08],
       [9.99986172e-01, 1.37962070e-05, 2.45720901e-08],
       [9.99929547e-01, 7.02409234e-05, 2.84154027e-07],
       [9.99967813e-01, 3.21215848e-05, 1.29530932e-07],
       [9.99988317e-01, 1.16467063e-05, 3.14223172e-08],
       [9.99981284e-01, 1.87606202e-05, 3.79605964e-08],
       [9.99998450e-01, 1.52906296e-06, 9.31258071e-10],
       [9.99989152e-01, 1.08259292e-05, 4.72976192e-09],
       [9.99873400e-01, 1.26226703e-04, 3.78452995e-07],
       [9.99992013e-01, 8.03670446e-06, 1.28057849e-08],
       [9.99954224e-01, 4.55002337e-05, 2.19017522e-07],
       [9.99990702e-01, 9.30542501e-06, 4.56174565e-09],
       [9.99959469e-01, 4.04255261e-05, 1.24512766e-07],
       [9.99991655e-01, 8.31321631e-06, 1.46961607e-08],
       [9.99992013e-01, 8.04176398e-06, 8.38180370e-09],
       [9.99963045e-01, 3.68700967e-05, 1.30135035e-07],
       [9.99972820e-01, 2.70057371e-05, 9.86296769e-08],
       [9.99976397e-01, 2.36207288e-05, 4.79016826e-08],
       [9.99986887e-01, 1.30672042e-05, 1.43807597e-08],
       [9.99986649e-01, 1.32966452e-05, 1.09543761e-08],
       [9.99998331e-01, 1.61965011e-06, 1.02514608e-09],
       [9.99977469e-01, 2.25241292e-05, 4.63424890e-08],
       [9.99962449e-01, 3.74417723e-05, 9.97159049e-08],
       [9.99945164e-01, 5.46964038e-05, 1.14547376e-07],
       [9.99993324e-01, 6.62223601e-06, 5.05895947e-09],
       [9.99992251e-01, 7.75174522e-06, 1.94554168e-08],
       [9.99983311e-01, 1.67030939e-05, 3.64581290e-08],
       [9.99970675e-01, 2.92263212e-05, 1.20037711e-07],
       [9.99988675e-01, 1.12739417e-05, 2.05322905e-08],
       [9.99989629e-01, 1.03968723e-05, 1.96366621e-08],
       [9.99989033e-01, 1.10201800e-05, 2.47655425e-08],
       [9.99951482e-01, 4.83417607e-05, 1.77975991e-07],
       [9.99991894e-01, 8.09080393e-06, 1.20937624e-08],
       [9.99993086e-01, 6.87362035e-06, 1.28740032e-08],
       [9.99985695e-01, 1.42469735e-05, 3.31469927e-08],
       [9.99946952e-01, 5.29834360e-05, 1.50100419e-07],
       [9.99981642e-01, 1.83383454e-05, 4.57871394e-08],
       [9.99990940e-01, 9.01224121e-06, 2.66343427e-08],
       [9.99971151e-01, 2.87223647e-05, 1.04172727e-07]], dtype=float32)>

In [23]:
w, b = dense.get_weights() # 학습되지 않음
print(w)
print('-'*40)
print(b)

[[ 0.4476303  -0.10155076 -0.67124176]
 [ 0.8930477  -0.8178235  -0.6296972 ]
 [-0.07882035 -0.31986266 -0.924294  ]
 [ 0.6552075   0.17981398  0.32426846]]
----------------------------------------
[0. 0. 0.]

In [24]:
z = tf.matmul(xdata, w) + b
hx = tf.nn.softmax(z)
hx.numpy().argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
dense = Dense(units=3, input_dim=4, activation='softmax') # units= y, input_dim= x
model = Sequential( [dense] )
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(xdata, ydata, epochs=500)

Epoch 1/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.3400 - loss: 4.5143
Epoch 2/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.3933 - loss: 1.9383
Epoch 3/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.4600 - loss: 1.9720
Epoch 4/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.4400 - loss: 1.0017
Epoch 5/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4800 - loss: 0.8326
Epoch 6/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.6200 - loss: 0.6256
Epoch 7/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8067 - loss: 0.4696
Epoch 8/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8400 - loss: 0.4709
Epoch 9/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7800 - loss: 0.4289
Epoch 10/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9067 - loss: 0.3889
Epoch 11/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8000 - loss: 0.3722
Epoch 12/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9067 - loss: 0.3556
Epoch 13/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9533 - loss: 0.3318
Epoch 14/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.3079
Epoch 15/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9600 - loss: 0.3005
Epoch 16/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9600 - loss: 0.2877
Epoch 17/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.2962
Epoch 18/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9200 - loss: 0.2927
Epoch 19/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9333 - loss: 0.2755
Epoch 20/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9533 - loss: 0.2644
Epoch 21/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9733 - loss: 0.2606
Epoch 22/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9267 - loss: 0.2492
Epoch 23/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9467 - loss: 0.2644
Epoch 24/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9400 - loss: 0.2369
Epoch 25/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.2308
Epoch 26/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9733 - loss: 0.2123
Epoch 27/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.2233
Epoch 28/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9533 - loss: 0.2110
Epoch 29/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9467 - loss: 0.2366
Epoch 30/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9533 - loss: 0.2026
Epoch 31/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9533 - loss: 0.2030
Epoch 32/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9867 - loss: 0.1873
Epoch 33/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9600 - loss: 0.1851
Epoch 34/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9667 - loss: 0.1899
Epoch 35/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9733 - loss: 0.1747
Epoch 36/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9600 - loss: 0.1781
Epoch 37/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9867 - loss: 0.1792
Epoch 38/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9667 - loss: 0.1699
Epoch 39/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9800 - loss: 0.1618
Epoch 40/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.1627
Epoch 41/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9667 - loss: 0.1680
Epoch 42/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9533 - loss: 0.1704
Epoch 43/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9667 - loss: 0.1683
Epoch 44/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9533 - loss: 0.1617
Epoch 45/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.1535
Epoch 46/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.1488
Epoch 47/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.1451
Epoch 48/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.1501
Epoch 49/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.1437
Epoch 50/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.1396
Epoch 51/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.1363
Epoch 52/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9800 - loss: 0.1357
Epoch 53/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.1402
Epoch 54/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.1538
Epoch 55/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9533 - loss: 0.1678
Epoch 56/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9600 - loss: 0.1396
Epoch 57/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9400 - loss: 0.1534
Epoch 58/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.1360
Epoch 59/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.1231
Epoch 60/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.1250
Epoch 61/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9733 - loss: 0.1250
Epoch 62/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.1235
Epoch 63/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.1213
Epoch 64/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.1182
Epoch 65/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9600 - loss: 0.1283
Epoch 66/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.1255
Epoch 67/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9733 - loss: 0.1164
Epoch 68/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.1162
Epoch 69/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9733 - loss: 0.1139
Epoch 70/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.1157
Epoch 71/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.1103
Epoch 72/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9667 - loss: 0.1153
Epoch 73/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.1149
Epoch 74/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.1111
Epoch 75/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.1097
Epoch 76/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9667 - loss: 0.1101
Epoch 77/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.1105
Epoch 78/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9667 - loss: 0.1151
Epoch 79/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.1021
Epoch 80/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9667 - loss: 0.1060
Epoch 81/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.1076
Epoch 82/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9667 - loss: 0.1110
Epoch 83/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9800 - loss: 0.1082
Epoch 84/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0984
Epoch 85/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.9600 - loss: 0.1172
Epoch 86/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0982
Epoch 87/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.1042
Epoch 88/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0964
Epoch 89/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0987
Epoch 90/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0976
Epoch 91/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9733 - loss: 0.0971
Epoch 92/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0975
Epoch 93/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.0939
Epoch 94/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0989
Epoch 95/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9800 - loss: 0.0968
Epoch 96/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0949
Epoch 97/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0916
Epoch 98/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9667 - loss: 0.0947
Epoch 99/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0893
Epoch 100/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9600 - loss: 0.0997
Epoch 101/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9733 - loss: 0.0932
Epoch 102/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0904
Epoch 103/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9733 - loss: 0.0932
Epoch 104/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0893
Epoch 105/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9867 - loss: 0.0878
Epoch 106/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9733 - loss: 0.0975
Epoch 107/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.0933
Epoch 108/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9800 - loss: 0.0874
Epoch 109/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9800 - loss: 0.0854
Epoch 110/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9733 - loss: 0.0862
Epoch 111/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9867 - loss: 0.0881
Epoch 112/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0960
Epoch 113/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.0926
Epoch 114/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9867 - loss: 0.0895
Epoch 115/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.0910
Epoch 116/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0878
Epoch 117/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0869
Epoch 118/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0858
Epoch 119/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.0824
Epoch 120/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9667 - loss: 0.0872
Epoch 121/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9600 - loss: 0.1151
Epoch 122/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0862
Epoch 123/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.0792
Epoch 124/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.0819
Epoch 125/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.0865
Epoch 126/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0768
Epoch 127/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9800 - loss: 0.0905
Epoch 128/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9667 - loss: 0.0972
Epoch 129/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0824
Epoch 130/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9867 - loss: 0.0824
Epoch 131/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9800 - loss: 0.0802
Epoch 132/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9733 - loss: 0.0794
Epoch 133/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.0780
Epoch 134/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0769
Epoch 135/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0823
Epoch 136/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9733 - loss: 0.0754
Epoch 137/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0798
Epoch 138/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0759
Epoch 139/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0750
Epoch 140/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0790
Epoch 141/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0773
Epoch 142/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0785
Epoch 143/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0747
Epoch 144/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9733 - loss: 0.0783
Epoch 145/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.0785
Epoch 146/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0773
Epoch 147/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.0800
Epoch 148/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0723
Epoch 149/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0753
Epoch 150/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9600 - loss: 0.1063
Epoch 151/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9533 - loss: 0.0934
Epoch 152/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9867 - loss: 0.0750
Epoch 153/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0809
Epoch 154/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9400 - loss: 0.1197
Epoch 155/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9867 - loss: 0.0972
Epoch 156/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.0884
Epoch 157/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9600 - loss: 0.0962
Epoch 158/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0811
Epoch 159/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0762
Epoch 160/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.0795
Epoch 161/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9800 - loss: 0.0704
Epoch 162/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9733 - loss: 0.0795
Epoch 163/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0705
Epoch 164/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0698
Epoch 165/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9667 - loss: 0.0788
Epoch 166/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0786
Epoch 167/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0775
Epoch 168/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0746
Epoch 169/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9733 - loss: 0.0771
Epoch 170/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9867 - loss: 0.0764
Epoch 171/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9867 - loss: 0.0693
Epoch 172/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.0815
Epoch 173/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9600 - loss: 0.0846
Epoch 174/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0690
Epoch 175/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9667 - loss: 0.0711
Epoch 176/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0821
Epoch 177/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9733 - loss: 0.0849
Epoch 178/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0711
Epoch 179/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0688
Epoch 180/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.0675
Epoch 181/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9800 - loss: 0.0675
Epoch 182/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0663
Epoch 183/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0661
Epoch 184/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9800 - loss: 0.0658
Epoch 185/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9800 - loss: 0.0681
Epoch 186/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9800 - loss: 0.0656
Epoch 187/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0690
Epoch 188/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9533 - loss: 0.0784
Epoch 189/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0825
Epoch 190/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9600 - loss: 0.0826
Epoch 191/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9800 - loss: 0.0740
Epoch 192/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9733 - loss: 0.0752
Epoch 193/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0641
Epoch 194/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0677
Epoch 195/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0719
Epoch 196/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9933 - loss: 0.0588
Epoch 197/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0789
Epoch 198/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.0759
Epoch 199/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9600 - loss: 0.0817
Epoch 200/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0725
Epoch 201/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9600 - loss: 0.0776
Epoch 202/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9667 - loss: 0.0787
Epoch 203/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.0760
Epoch 204/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9800 - loss: 0.0679
Epoch 205/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9867 - loss: 0.0675
Epoch 206/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9800 - loss: 0.0668
Epoch 207/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9600 - loss: 0.0793
Epoch 208/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9800 - loss: 0.0648
Epoch 209/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0631
Epoch 210/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0689
Epoch 211/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9733 - loss: 0.0620
Epoch 212/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9733 - loss: 0.0656
Epoch 213/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0739
Epoch 214/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.0745
Epoch 215/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9867 - loss: 0.0668
Epoch 216/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0650
Epoch 217/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.0879
Epoch 218/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9733 - loss: 0.0749
Epoch 219/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0583
Epoch 220/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9600 - loss: 0.0781
Epoch 221/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9867 - loss: 0.0611
Epoch 222/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9867 - loss: 0.0681
Epoch 223/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0654
Epoch 224/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0606
Epoch 225/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0610
Epoch 226/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9800 - loss: 0.0624
Epoch 227/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0636
Epoch 228/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9733 - loss: 0.0639
Epoch 229/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0610
Epoch 230/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0609
Epoch 231/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0600
Epoch 232/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9800 - loss: 0.0598
Epoch 233/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9800 - loss: 0.0610
Epoch 234/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0611
Epoch 235/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9733 - loss: 0.0677
Epoch 236/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0609
Epoch 237/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9867 - loss: 0.0635
Epoch 238/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9667 - loss: 0.0774
Epoch 239/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9667 - loss: 0.0654
Epoch 240/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9867 - loss: 0.0559
Epoch 241/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9733 - loss: 0.0692
Epoch 242/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9667 - loss: 0.0674
Epoch 243/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9800 - loss: 0.0611
Epoch 244/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0639
Epoch 245/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9800 - loss: 0.0625
Epoch 246/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0591
Epoch 247/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9800 - loss: 0.0609
Epoch 248/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9800 - loss: 0.0655
Epoch 249/500

In [26]:
model.predict(xdata[[0,1]]).argmax(axis=1) # 2X4 4X3

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

array([0, 0])