In [457]:
import numpy as np
import pandas as pd

## 청년인구 증감율(%)

In [458]:
youth = pd.read_csv('../../pre_note/seoha/data/인구총조사_19-39_2015-2024.csv')
youth

       연도     행정구역     19세   20~24세   25~29세   30~34세   35~39세
0    2015       전국  671216  3385936  3027896  3611034  3783589
1    2015    서울특별시  121531   681199   722350   823935   767625
2    2015    부산광역시   48246   241138   203729   232762   240788
3    2015    대구광역시   35472   175680   141245   159794   175062
4    2015    인천광역시   36518   195760   180149   215364   225552
..    ...      ...     ...      ...      ...      ...      ...
175  2024  전북특별자치도   15725    90731    91785    86910    80797
176  2024     전라남도   10266    69515    84588    82877    78696
177  2024     경상북도   20579   115516   122422   125646   123466
178  2024     경상남도   21188   131838   156211   167753   168782
179  2024  제주특별자치도    4473    28706    35505    38543    36387

[180 rows x 7 columns]

In [459]:
youth = youth[youth['행정구역'] != '전국'].copy()

In [460]:
youth = youth[~youth['행정구역'].str.contains('전국', na=False)].copy()

In [461]:
youth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 170 entries, 1 to 179
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      170 non-null    int64
 1   행정구역    170 non-null    object
 2   19세     170 non-null    int64
 3   20~24세  170 non-null    int64
 4   25~29세  170 non-null    int64
 5   30~34세  170 non-null    int64
 6   35~39세  170 non-null    int64
dtypes: int64(6), object(1)
memory usage: 10.6+ KB

In [462]:
youth['청년_19_29'] = (youth['19세'] + youth['20~24세'] + youth['25~29세'])
youth['청년_19_29']

1      1525080
2       493113
3       352397
4       412427
5       227717
        ...
175     198241
176     164369
177     258517
178     309237
179      68684
Name: 청년_19_29, Length: 170, dtype: int64

In [463]:
youth['청년_30_39'] = (youth['30~34세'] + youth['35~39세'])
youth['청년_30_39']

1      1591560
2       473550
3       334856
4       440916
5       222729
        ...
175     167707
176     161573
177     249112
178     336535
179      74930
Name: 청년_30_39, Length: 170, dtype: int64

In [464]:
youth = youth.sort_values(by=['행정구역', '연도'])

In [465]:
youth['청년_19_29_증감률(%)'] = (youth.groupby('행정구역')['청년_19_29'].pct_change() * 100)

In [466]:
youth['청년_30_39_증감률(%)'] = (youth.groupby('행정구역')['청년_30_39'].pct_change() * 100)

In [467]:
youth[
    ['연도', '행정구역',
    '청년_19_29', '청년_19_29_증감률(%)',
    '청년_30_39', '청년_30_39_증감률(%)']
].head(12)

       연도     행정구역  청년_19_29  청년_19_29_증감률(%)  청년_30_39  청년_30_39_증감률(%)
10   2015  강원특별자치도    203280              NaN    181829              NaN
28   2016  강원특별자치도    205617         1.149646    178064        -2.070627
46   2017  강원특별자치도    204484        -0.551024    173052        -2.814718
64   2018  강원특별자치도    202710        -0.867550    168657        -2.539699
82   2019  강원특별자치도    200437        -1.121306    164479        -2.477217
100  2020  강원특별자치도    196648        -1.890370    160343        -2.514607
118  2021  강원특별자치도    191104        -2.819251    157147        -1.993227
136  2022  강원특별자치도    187312        -1.984260    155331        -1.155606
154  2023  강원특별자치도    180885        -3.431174    153744        -1.021689
172  2024  강원특별자치도    171760        -5.044642    153756         0.007805
9    2015      경기도   1693539              NaN   1898035              NaN
27   2016      경기도   1724364         1.820153   1883363        -0.773010

In [468]:
order = [
    '서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시','울산광역시',
    '세종특별자치시','경기도','강원특별자치도','충청북도','충청남도','전북특별자치도','전라남도',
    '경상북도','경상남도','제주특별자치도'
]

youth['행정구역'] = pd.Categorical(
    youth['행정구역'],
    categories=order,
    ordered=True
)

# 계산용 정렬
youth = youth.sort_values(by=['행정구역', '연도'])
youth

,연도,행정구역,19세,20~24세,25~29세,30~34세,35~39세,청년_19_29,청년_30_39,청년_19_29_증감률(%),청년_30_39_증감률(%)
1,2015,서울특별시,121531,681199,722350,823935,767625,1525080,1591560,NaN,NaN
19,2016,서울특별시,117053,673957,720334,772614,773379,1511344,1545993,-0.900674,-2.863040
37,2017,서울특별시,112538,661569,735323,727683,777632,1509430,1505315,-0.126642,-2.631189
55,2018,서울특별시,106752,645569,755906,696267,772520,1508227,1468787,-0.079699,-2.426602
73,2019,서울특별시,110312,630814,777456,685989,745331,1518582,1431320,0.686568,-2.550880
...,...,...,...,...,...,...,...,...,...,...,...
107,2020,제주특별자치도,6291,36772,38934,33811,45994,81997,79805,2.544959,-2.575841
125,2021,제주특별자치도,5372,34893,39493,34757,43494,79758,78251,-2.730588,-1.947246
143,2022,제주특별자치도,5343,32757,38912,36160,40779,77012,76939,-3.442915,-1.676656
161,2023,제주특별자치도,4955,30397,37359,37639,37921,72711,75560,-5.584844,-1.792329
179,2024,제주특별자치도,4473,28706,35505,38543,36387,68684,74930,-5.538364,-0.833774

In [ ]:
cols = [
    '연도', '행정구역',
    '청년_19_29', '청년_19_29_증감률(%)',
    '청년_30_39', '청년_30_39_증감률(%)'
]

In [470]:
youth['행정구역'].isna().sum(), (youth['행정구역'].astype(str).str.strip() == '').sum()

(np.int64(0), np.int64(0))

In [471]:
youth.columns.tolist()

['연도',
 '행정구역',
 '19세',
 '20~24세',
 '25~29세',
 '30~34세',
 '35~39세',
 '청년_19_29',
 '청년_30_39',
 '청년_19_29_증감률(%)',
 '청년_30_39_증감률(%)']

In [472]:
youth

,연도,행정구역,19세,20~24세,25~29세,30~34세,35~39세,청년_19_29,청년_30_39,청년_19_29_증감률(%),청년_30_39_증감률(%)
1,2015,서울특별시,121531,681199,722350,823935,767625,1525080,1591560,NaN,NaN
19,2016,서울특별시,117053,673957,720334,772614,773379,1511344,1545993,-0.900674,-2.863040
37,2017,서울특별시,112538,661569,735323,727683,777632,1509430,1505315,-0.126642,-2.631189
55,2018,서울특별시,106752,645569,755906,696267,772520,1508227,1468787,-0.079699,-2.426602
73,2019,서울특별시,110312,630814,777456,685989,745331,1518582,1431320,0.686568,-2.550880
...,...,...,...,...,...,...,...,...,...,...,...
107,2020,제주특별자치도,6291,36772,38934,33811,45994,81997,79805,2.544959,-2.575841
125,2021,제주특별자치도,5372,34893,39493,34757,43494,79758,78251,-2.730588,-1.947246
143,2022,제주특별자치도,5343,32757,38912,36160,40779,77012,76939,-3.442915,-1.676656
161,2023,제주특별자치도,4955,30397,37359,37639,37921,72711,75560,-5.584844,-1.792329
179,2024,제주특별자치도,4473,28706,35505,38543,36387,68684,74930,-5.538364,-0.833774

In [473]:
base = pd.read_csv('../../data/busan_youth_v2.csv', index_col='Unnamed: 0')
base.head(3)

,연도,행정구역,연앙인구수(천명),지역내총생산,재정자립도(%),통계방식변경,제조업종사자수,상용월평균급여(원),문화예술활동(건),대학수(천명당),문화기반시설수(십만명당),전체산업종사자수(천명당),기업밀도,지역내총생산(십억원)
18,2016,강원특별자치도,1536.2750,44677444.0,22.40,0.0,57365.0,3023906.0,1444.0,0.012368,13.734520,388.413533,351.305988,44677.444
19,2016,경기도,12509.4835,433443961.0,61.61,0.0,1276105.0,3328379.0,3925.0,0.006235,4.028943,383.915851,2230.077238,433443.961
20,2016,경상남도,3348.2515,113497638.0,36.61,0.0,433488.0,3257296.0,1689.0,0.007168,5.764203,411.869001,652.882347,113497.638

In [474]:
rate_cols = youth[[
    '연도', '행정구역',
    '청년_19_29_증감률(%)',
    '청년_30_39_증감률(%)'
]]

In [475]:
merged = base.merge(
    rate_cols,
    on=['연도', '행정구역'],
    how='left'
)

In [476]:
merged = merged.drop(merged[merged['연도'] == 2015].index)
merged = merged.drop(merged[merged['연도'] == 2025].index)

In [477]:
merged.head()

,연도,행정구역,연앙인구수(천명),지역내총생산,재정자립도(%),통계방식변경,제조업종사자수,상용월평균급여(원),문화예술활동(건),대학수(천명당),문화기반시설수(십만명당),전체산업종사자수(천명당),기업밀도,지역내총생산(십억원),청년_19_29_증감률(%),청년_30_39_증감률(%)
0,2016,강원특별자치도,1536.2750,44677444.0,22.40,0.0,57365.0,3023906.0,1444.0,0.012368,13.734520,388.413533,351.305988,44677.444,1.149646,-2.070627
1,2016,경기도,12509.4835,433443961.0,61.61,0.0,1276105.0,3328379.0,3925.0,0.006235,4.028943,383.915851,2230.077238,433443.961,1.820153,-0.773010
2,2016,경상남도,3348.2515,113497638.0,36.61,0.0,433488.0,3257296.0,1689.0,0.007168,5.764203,411.869001,652.882347,113497.638,-0.054546,-2.108272
3,2016,경상북도,2683.4775,112216094.0,26.10,0.0,328962.0,3326347.0,1035.0,0.014533,7.266690,404.936505,549.557763,112216.094,-0.105801,-2.177146
4,2016,광주광역시,1461.5310,39427386.0,46.68,0.0,85157.0,2994355.0,1284.0,0.012316,3.900020,400.597729,289.682121,39427.386,-0.390397,-3.492136

In [478]:
# 현재 컬럼 순서 확인
merged.columns

Index(['연도', '행정구역', '연앙인구수(천명)', '지역내총생산', '재정자립도(%)', '통계방식변경', '제조업종사자수',
       '상용월평균급여(원)', '문화예술활동(건)', '대학수(천명당)', '문화기반시설수(십만명당)', '전체산업종사자수(천명당)',
       '기업밀도', '지역내총생산(십억원)', '청년_19_29_증감률(%)', '청년_30_39_증감률(%)'],
      dtype='object')

In [479]:
merged

,연도,행정구역,연앙인구수(천명),지역내총생산,재정자립도(%),통계방식변경,제조업종사자수,상용월평균급여(원),문화예술활동(건),대학수(천명당),문화기반시설수(십만명당),전체산업종사자수(천명당),기업밀도,지역내총생산(십억원),청년_19_29_증감률(%),청년_30_39_증감률(%)
0,2016,강원특별자치도,1536.2750,44677444.0,22.40,0.0,57365.0,3023906.0,1444.0,0.012368,13.734520,388.413533,351.305988,44677.444,1.149646,-2.070627
1,2016,경기도,12509.4835,433443961.0,61.61,0.0,1276105.0,3328379.0,3925.0,0.006235,4.028943,383.915851,2230.077238,433443.961,1.820153,-0.773010
2,2016,경상남도,3348.2515,113497638.0,36.61,0.0,433488.0,3257296.0,1689.0,0.007168,5.764203,411.869001,652.882347,113497.638,-0.054546,-2.108272
3,2016,경상북도,2683.4775,112216094.0,26.10,0.0,328962.0,3326347.0,1035.0,0.014533,7.266690,404.936505,549.557763,112216.094,-0.105801,-2.177146
4,2016,광주광역시,1461.5310,39427386.0,46.68,0.0,85157.0,2994355.0,1284.0,0.012316,3.900020,400.597729,289.682121,39427.386,-0.390397,-3.492136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,2024,전라남도,1792.3250,103970897.0,24.40,1.0,128939.0,4034870.0,1438.0,0.010601,13.390429,501.920132,504.474684,103970.897,-5.046648,-0.016089
149,2024,전북특별자치도,1741.6360,66792381.0,23.51,1.0,119854.0,3736595.0,1839.0,0.011483,10.794448,469.189314,537.972610,66792.381,-5.533847,-0.308514
150,2024,제주특별자치도,669.0510,26928491.0,34.01,1.0,12905.0,3501134.0,1053.0,0.005979,18.832645,494.285189,202.652238,26928.491,-5.538364,-0.833774
151,2024,충청남도,2126.6115,150681268.0,32.35,1.0,314597.0,4680157.0,1832.0,0.011286,9.357610,527.287189,545.099532,150681.268,-2.439551,0.305802
152,2024,충청북도,1587.7145,91794456.0,30.43,1.0,228821.0,3956021.0,1313.0,0.011337,8.943673,542.862083,383.504405,91794.456,-4.867564,0.721361

In [ ]:
merged.to_csv(
    '../../../notebooks/data/busan_youth_v3.csv',
    index=False,
    encoding='utf-8-sig'
)

In [481]:
merged.columns

Index(['연도', '행정구역', '연앙인구수(천명)', '지역내총생산', '재정자립도(%)', '통계방식변경', '제조업종사자수',
       '상용월평균급여(원)', '문화예술활동(건)', '대학수(천명당)', '문화기반시설수(십만명당)', '전체산업종사자수(천명당)',
       '기업밀도', '지역내총생산(십억원)', '청년_19_29_증감률(%)', '청년_30_39_증감률(%)'],
      dtype='object')